"""
Process covariance matrices generated by `generate_snapshots.py` / `f_gendata.py`:
- Support covariance npy with shape (T, N, N) *or* (num_sets, T, N, N), complex128.
- Mean over snapshot dimension T -> sample covariance of shape (num_sets, N, N).
- H 由含噪协方差均值计算（保持原逻辑）；U/S/Vh 改为无噪协方差均值的 SVD 结果。
- Save truncated U/S/Vh，以及按 r=0..rank_dim-1 依次“置零前 r 个最大奇异值”重构得到的 H，形状 (num_sets, rank_dim, N, N, 2)，
    文件名沿用 `set_dataset_filename` 后缀（不含 num_sets）。
"""

import argparse
from pathlib import Path
from typing import Tuple
from itertools import permutations

import numpy as np

# numpy memmap helper
from numpy.lib.format import open_memmap

from src.system_model import SystemModelParams
from src.data_handler import set_dataset_filename


def _build_params(
    N: int,
    M: int,
    T: int,
    snr: float,
    signal_type: str,
    signal_nature: str,
    eta: float,
    bias: float,
    sv_noise_var: float,
    doa_gap: float = 15.0,
    fixed_gap: bool = False,
) -> SystemModelParams:
    """Create SystemModelParams with provided fields."""

    return (
        SystemModelParams()
        .set_parameter("N", N)
        .set_parameter("M", M)
        .set_parameter("T", T)
        .set_parameter("snr", snr)
        .set_parameter("signal_type", signal_type)
        .set_parameter("signal_nature", signal_nature)
        .set_parameter("eta", eta)
        .set_parameter("bias", bias)
        .set_parameter("sv_noise_var", sv_noise_var)
        .set_parameter("doa_gap", doa_gap)
        .set_parameter("fixed_gap", fixed_gap)
    )


def _build_suffix(params: SystemModelParams, samples_size: int) -> str:
    """Suffix consistent with dataset naming (no .h5)."""

    return set_dataset_filename(params, samples_size).replace(".h5", "")


def load_covariances(input_dir: Path, suffix: str, *, clean: bool = False) -> np.ndarray:
    fname = "covariances_clean" if clean else "covariances"
    cov_path = input_dir / f"{fname}{suffix}.npy"
    if not cov_path.exists():
        raise FileNotFoundError(f"Covariance file not found: {cov_path}")
    covs = np.load(cov_path)
    if covs.ndim == 3:
        # (T, N, N) -> add batch dim of 1 for unified handling
        covs = covs[np.newaxis, ...]
    if covs.ndim != 4:
        raise ValueError(f"Expect {fname} with shape (T, N, N) or (num_sets, T, N, N), got {covs.shape}")
    return covs


def svd_truncate_mean(covs_noisy: np.ndarray, covs_clean: np.ndarray, rank: int, out_dir: Path, suffix: str):
    """Mean over T then SVD per set, splitting noisy vs clean usage.

    - H: from noisy sample covariance
    - U/S/Vh: from clean sample covariance

    Args:
        covs_noisy: (num_sets, T, N, N) complex ndarray.
        covs_clean: (num_sets, T, N, N) complex ndarray.
        rank: truncation rank.
        out_dir: directory to place memmap npy files.
        suffix: filename suffix.

    Returns:
        Paths to memmap npy files: (U_path, S_path, Vh_path, H_path)
    """

    out_dir.mkdir(parents=True, exist_ok=True)

    num_sets, T, N, _ = covs_noisy.shape

    # sample covariance: mean over T
    cov_mean_noisy = covs_noisy.mean(axis=1)  # (num_sets, N, N)
    cov_mean_clean = covs_clean.mean(axis=1)

    U_path = out_dir / f"svd_U{suffix}.npy"
    S_path = out_dir / f"svd_S{suffix}.npy"
    Vh_path = out_dir / f"svd_Vh{suffix}.npy"
    H_path = out_dir / f"svd_H{suffix}.npy"

    U_mm = open_memmap(U_path, mode="w+", dtype=np.float64, shape=(num_sets, N, rank, 2))
    S_mm = open_memmap(S_path, mode="w+", dtype=np.float64, shape=(num_sets, rank))
    Vh_mm = open_memmap(Vh_path, mode="w+", dtype=np.float64, shape=(num_sets, rank, N, 2))
    H_mm = open_memmap(H_path, mode="w+", dtype=np.float64, shape=(num_sets, rank, N, N, 2))

    for s in range(num_sets):
        # clean covariance for U/S/Vh
        C_clean = cov_mean_clean[s].astype(np.complex128, copy=False)
        U, S, Vh = np.linalg.svd(C_clean, full_matrices=False)
        U_r = U[:, :rank]
        S_r = S[:rank]
        Vh_r = Vh[:rank, :]

        # noisy covariance SVD (compute once per set)
        C_noisy = cov_mean_noisy[s].astype(np.complex128, copy=False)
        U_n, S_n, Vh_n = np.linalg.svd(C_noisy, full_matrices=False)

        H_rec_per_rank = []
        for r in range(rank):
            # noisy covariance for H reconstruction (zeroing top-r sigmas)
            S_masked = S_n.copy()
            S_masked[:r] = 0.0
            H_rec = (U_n * S_masked.reshape(1, -1)) @ Vh_n
            H_rec_per_rank.append(H_rec)
        H_rec_per_rank = np.stack(H_rec_per_rank, axis=0)  # (rank, N, N)

        U_mm[s, :, :, 0] = U_r.real
        U_mm[s, :, :, 1] = U_r.imag
        S_mm[s, :] = S_r
        Vh_mm[s, :, :, 0] = Vh_r.real
        Vh_mm[s, :, :, 1] = Vh_r.imag
        H_mm[s, :, :, :, 0] = H_rec_per_rank.real
        H_mm[s, :, :, :, 1] = H_rec_per_rank.imag

    U_mm.flush(); S_mm.flush(); Vh_mm.flush(); H_mm.flush()
    return U_path, S_path, Vh_path, H_path


def _to_ri(x: np.ndarray) -> np.ndarray:
    """complex ndarray -> real/imag stacked at last dim."""
    return np.stack([x.real, x.imag], axis=-1).astype(np.float64, copy=False)


def _to_complex_ri(x_ri: np.ndarray) -> np.ndarray:
    """real/imag stacked at last dim -> complex ndarray."""
    if x_ri.shape[-1] != 2:
        raise ValueError(f"Expect real/imag with last dim=2, got {x_ri.shape}")
    return x_ri[..., 0] + 1j * x_ri[..., 1]


def _as_bool(v) -> bool:
    """Robust bool parser for argparse values that may be bool or str."""
    if isinstance(v, bool):
        return v
    if v is None:
        return False
    if isinstance(v, (int, float)):
        return bool(v)
    s = str(v).strip().lower()
    if s in {"1", "true", "t", "yes", "y", "on"}:
        return True
    if s in {"0", "false", "f", "no", "n", "off"}:
        return False
    return bool(v)


def _unitnorm_cols(X: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    """Normalize columns of a 2D complex matrix."""
    den = np.sqrt(np.sum(np.abs(X) ** 2, axis=0, keepdims=True)) + eps
    return X / den


def _best_assignment_by_abs_correlation(U: np.ndarray, A: np.ndarray) -> np.ndarray:
    """Find permutation pi that best matches columns of U to columns of A.

    Args:
        U: (N,K) complex columns (target eigenvectors), K>=1
        A: (N,M) complex columns (steering vectors), M>=1
    Returns:
        pi: (K,) int array mapping U[:,i] -> A[:,pi[i]]

    Notes:
        - Uses brute-force permutations; intended for small K (typical #sources).
        - Score_ij = |<u_i, a_j>| / (||u_i|| ||a_j||)
        - If M < K, match only first M and keep remaining as -1.
    """
    if U.ndim != 2 or A.ndim != 2:
        raise ValueError(f"Expect U/A as 2D matrices, got {U.shape} / {A.shape}")
    N, K = U.shape
    N2, M = A.shape
    if N != N2:
        raise ValueError(f"Dimension mismatch: U is {U.shape}, A is {A.shape}")

    K_eff = min(K, M)
    if K_eff <= 0:
        return -np.ones((K,), dtype=np.int64)

    Uu = _unitnorm_cols(U[:, :K_eff])
    Au = _unitnorm_cols(A)
    # (K_eff, M)
    score = np.abs(Uu.conj().T @ Au)

    best = None
    best_val = -1.0
    for perm in permutations(range(M), K_eff):
        val = 0.0
        for i, j in enumerate(perm):
            val += float(score[i, j])
        if val > best_val:
            best_val = val
            best = np.array(perm, dtype=np.int64)

    pi = -np.ones((K,), dtype=np.int64)
    pi[:K_eff] = best
    return pi


def align_doa_to_u_targets(
    generated_dir: Path,
    processed_dir: Path,
    suffix: str,
    rank: int,
    *,
    steering_filename: str = "steering_vectors",
    prefer_clean_steering: bool = True,
    doa_filename: str = "doas",
    save_reordered_steering: bool = True,
) -> tuple[Path, Path | None]:
    """Align per-set DoA order to match iter_u_target order, and save a new aligned DoA file.

    This function is meant to run *after* `generate_iterative_teacher_data`, so we can
    read `iter_u_target{suffix}.npy` as the U order reference.

    Inputs:
      - generated_dir/doas{suffix}.npy:           (num_sets, M) in radians
      - generated_dir/steering_vectors{suffix}.npy: (num_sets, N, M) complex
      - processed_dir/iter_u_target{suffix}.npy:  (num_sets, rank, N, 2)

    Outputs:
      - generated_dir/doas_aligned{suffix}.npy: (num_sets, rank) radians (aligned to u_target)
      - (optional) generated_dir/steering_vectors_aligned{suffix}.npy: (num_sets, N, rank)
    """

    generated_dir = Path(generated_dir)
    processed_dir = Path(processed_dir)
    u_path = processed_dir / f"iter_u_target{suffix}.npy"
    doa_path = generated_dir / f"{doa_filename}{suffix}.npy"

    # Prefer clean steering vectors if provided by f_gendata.py
    sv_path = generated_dir / f"{steering_filename}{suffix}.npy"
    if prefer_clean_steering:
        sv_clean_path = generated_dir / f"{steering_filename}_clean{suffix}.npy"
        if sv_clean_path.exists():
            sv_path = sv_clean_path
    if not u_path.exists():
        raise FileNotFoundError(f"Missing iter_u_target file: {u_path}")
    if not doa_path.exists():
        raise FileNotFoundError(f"Missing doa file: {doa_path}")
    if not sv_path.exists():
        raise FileNotFoundError(f"Missing steering_vectors file: {sv_path}")

    u_ri = np.load(u_path, mmap_mode="r")  # (num_sets, rank, N, 2)
    doas = np.load(doa_path)               # (num_sets, M)
    sv = np.load(sv_path)                  # (num_sets, N, M) complex

    if u_ri.ndim != 4 or u_ri.shape[-1] != 2:
        raise ValueError(f"Expect iter_u_target shape (num_sets, rank, N, 2), got {u_ri.shape}")
    num_sets, K, N, _ = u_ri.shape
    if int(K) != int(rank):
        # keep it robust: rank argument should match file's step dimension
        rank = int(K)
    if doas.shape[0] != num_sets:
        m = min(int(doas.shape[0]), int(num_sets))
        doas = doas[:m]
        sv = sv[:m]
        u_ri = u_ri[:m]
        num_sets = m
    if sv.ndim != 3 or sv.shape[1] != N:
        raise ValueError(f"Expect steering_vectors (num_sets, N, M), got {sv.shape}")

    # Align: for each set, match U targets to steering columns
    doas_aligned = np.zeros((num_sets, rank), dtype=np.float64)
    sv_aligned = np.zeros((num_sets, N, rank), dtype=np.complex128) if save_reordered_steering else None

    for s in range(num_sets):
        Uc = _to_complex_ri(np.array(u_ri[s], dtype=np.float64, copy=False))  # (rank, N) complex? actually (rank,N)
        # convert to (N, rank)
        Uc = Uc.reshape(rank, N).T
        A = np.array(sv[s], dtype=np.complex128, copy=False)  # (N, M)
        pi = _best_assignment_by_abs_correlation(Uc, A)  # (rank,)
        for i in range(rank):
            j = int(pi[i])
            if j < 0:
                doas_aligned[s, i] = 0.0
                if sv_aligned is not None:
                    sv_aligned[s, :, i] = 0.0
            else:
                doas_aligned[s, i] = float(doas[s, j])
                if sv_aligned is not None:
                    sv_aligned[s, :, i] = A[:, j]

    doa_out = generated_dir / f"doas_aligned{suffix}.npy"
    np.save(doa_out, doas_aligned)

    sv_out = None
    if sv_aligned is not None:
        # Output name indicates which steering source was used.
        stem = Path(sv_path).stem  # e.g., steering_vectors_clean{suffix} or steering_vectors{suffix}
        # Remove suffix part from stem to keep filename short
        # We only keep prefix: steering_vectors(_clean)?
        prefix = "steering_vectors_aligned"
        if "clean" in stem:
            prefix = "steering_vectors_clean_aligned"
        sv_out = generated_dir / f"{prefix}{suffix}.npy"
        np.save(sv_out, sv_aligned)

    return doa_out, sv_out


def generate_iterative_teacher_data(
    covs_noisy: np.ndarray,
    covs_clean: np.ndarray,
    rank: int,
    out_dir: Path,
    suffix: str,
):
    """Generate teacher-forcing data for iterative (route-A) training.

    Targets come from CLEAN covariance eigenvectors. Step-wise residuals are built
    by projecting out the TRUE clean directions (teacher forcing), so training input
    distribution stays stable.

    Saved files (float64, real/imag format):
    - iter_cov_clean{suffix}.npy:        (num_sets, N, N, 2)
    - iter_cov_noisy{suffix}.npy:        (num_sets, N, N, 2)
    - iter_u_target{suffix}.npy:         (num_sets, rank, N, 2)
    - iter_cov_clean_step{suffix}.npy:   (num_sets, rank, N, N, 2)   residuals before removing each u_i
    - iter_cov_noisy_step{suffix}.npy:   (num_sets, rank, N, N, 2)   noisy residuals (deflated with clean projectors)
    """

    out_dir.mkdir(parents=True, exist_ok=True)
    num_sets, T, N, _ = covs_noisy.shape

    cov_mean_noisy = covs_noisy.mean(axis=1).astype(np.complex128, copy=False)
    cov_mean_clean = covs_clean.mean(axis=1).astype(np.complex128, copy=False)

    cov_clean_path = out_dir / f"iter_cov_clean{suffix}.npy"
    cov_noisy_path = out_dir / f"iter_cov_noisy{suffix}.npy"
    u_tgt_path = out_dir / f"iter_u_target{suffix}.npy"
    u_tgt_noisy_path = out_dir / f"iter_u_target_noisy{suffix}.npy"  # 新增：noisy target
    cov_clean_step_path = out_dir / f"iter_cov_clean_step{suffix}.npy"
    cov_noisy_step_path = out_dir / f"iter_cov_noisy_step{suffix}.npy"

    cov_clean_mm = open_memmap(cov_clean_path, mode="w+", dtype=np.float64, shape=(num_sets, N, N, 2))
    cov_noisy_mm = open_memmap(cov_noisy_path, mode="w+", dtype=np.float64, shape=(num_sets, N, N, 2))
    u_tgt_mm = open_memmap(u_tgt_path, mode="w+", dtype=np.float64, shape=(num_sets, rank, N, 2))
    u_tgt_noisy_mm = open_memmap(u_tgt_noisy_path, mode="w+", dtype=np.float64, shape=(num_sets, rank, N, 2))  # 新增
    cov_clean_step_mm = open_memmap(cov_clean_step_path, mode="w+", dtype=np.float64, shape=(num_sets, rank, N, N, 2))
    cov_noisy_step_mm = open_memmap(cov_noisy_step_path, mode="w+", dtype=np.float64, shape=(num_sets, rank, N, N, 2))

    I = np.eye(N, dtype=np.complex128)

    for s in range(num_sets):
        Rn0 = cov_mean_noisy[s]
        Rc0 = cov_mean_clean[s]

        # SVD on clean covariance -> target directions
        Uc, _, _ = np.linalg.svd(Rc0, full_matrices=False)
        Uc_r = Uc[:, :rank]  # (N, rank)

        # noisy covariance -> target directions (新增)
        Un, _, _ = np.linalg.svd(Rn0, full_matrices=False)
        Un_r = Un[:, :rank]  # (N, rank)

        cov_clean_mm[s] = _to_ri(Rc0)
        cov_noisy_mm[s] = _to_ri(Rn0)

        Rc = Rc0
        Rn = Rn0
        for i in range(rank):
            # residual BEFORE removing u_i
            cov_clean_step_mm[s, i] = _to_ri(Rc)
            cov_noisy_step_mm[s, i] = _to_ri(Rn)

            ui = Uc_r[:, i]
            u_tgt_mm[s, i, :, 0] = ui.real
            u_tgt_mm[s, i, :, 1] = ui.imag

            # 保存 noisy target（新增）
            ui_noisy = Un_r[:, i]
            u_tgt_noisy_mm[s, i, :, 0] = ui_noisy.real
            u_tgt_noisy_mm[s, i, :, 1] = ui_noisy.imag

            ui_col = ui.reshape(N, 1)
            P = ui_col @ ui_col.conj().T
            P_perp = I - P
            Rc = P_perp @ Rc @ P_perp
            Rn = P_perp @ Rn @ P_perp
            Rc = 0.5 * (Rc + Rc.conj().T)
            Rn = 0.5 * (Rn + Rn.conj().T)

    cov_clean_mm.flush(); cov_noisy_mm.flush(); u_tgt_mm.flush(); u_tgt_noisy_mm.flush(); cov_clean_step_mm.flush(); cov_noisy_step_mm.flush()
    return cov_clean_path, cov_noisy_path, u_tgt_path, u_tgt_noisy_path, cov_clean_step_path, cov_noisy_step_path


def save_outputs(output_dir: Path, suffix: str, U: np.ndarray, S: np.ndarray, Vh: np.ndarray, H: np.ndarray):
    output_dir.mkdir(parents=True, exist_ok=True)
    np.save(output_dir / f"svd_U{suffix}.npy", U)
    np.save(output_dir / f"svd_S{suffix}.npy", S)
    np.save(output_dir / f"svd_Vh{suffix}.npy", Vh)
    np.save(output_dir / f"svd_H{suffix}.npy", H)
    print(
        f"Saved: U->svd_U{suffix}.npy (shape {U.shape}), "
        f"S->svd_S{suffix}.npy (shape {S.shape}), "
        f"Vh->svd_Vh{suffix}.npy (shape {Vh.shape}), "
        f"H->svd_H{suffix}.npy (shape {H.shape})"
    )


def validate(
    path_dir: Path = Path("datasets/processed_cov_svd"),
    N: int = 8,
    M: int = 3,
    T: int = 100,
    snr: float = 10,
    signal_type: str = "NarrowBand",
    signal_nature: str = "non-coherent",
    eta: float = 0.0,
    bias: float = 0.0,
    sv_noise_var: float = 0.0,
    doa_gap: float = 15.0,
    fixed_gap: bool = False,
):
    print(f"\nValidating {path_dir}")
    data_dir = path_dir
    # 查看数据维度
    params = _build_params(
        N=N,
        M=M,
        T=T,
        snr=snr,
        signal_type=signal_type,
        signal_nature=signal_nature,
        eta=eta,
        bias=bias,
        sv_noise_var=sv_noise_var,
        doa_gap=doa_gap,
        fixed_gap=fixed_gap,
    )
    suffix = _build_suffix(params, params.T)
    U_file = data_dir / f"svd_U{suffix}.npy"
    S_file = data_dir / f"svd_S{suffix}.npy"
    V_file = data_dir / f"svd_Vh{suffix}.npy"
    H_file = data_dir / f"svd_H{suffix}.npy"
    U = np.load(U_file)
    S = np.load(S_file)
    V = np.load(V_file)
    H = np.load(H_file)
    print(f"U shape: {U.shape}")
    print(f"S shape: {S.shape}")
    print(f"Vh shape: {V.shape}")
    print(f"H shape: {H.shape}")

# 要修改进行SVD数据生成的数据，就在这里修改即可
def _build_arg_parser(N = 8, M = 3, T = 100, snr = 30, signal_type = "NarrowBand", signal_nature = "non-coherent", eta = 0.0, bias = 0.0, sv_noise_var = 0.0, rank = 3, save_iterative_data = False, fixed_gap = True) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="SVD-truncate covariance matrices generated by f_gendata.py")
    parser.add_argument("--input_dir", type=str, default="datasets/generated_snapshots", help="Folder containing covariances*.npy")
    parser.add_argument("--output_dir", type=str, default="datasets/processed_cov_svd", help="Folder to save truncated SVD outputs")
    parser.add_argument("--N", type=int, default=N)
    parser.add_argument("--M", type=int, default=M)
    parser.add_argument("--T", type=int, default=T)
    parser.add_argument("--snr", type=float, default=snr)
    parser.add_argument("--signal_type", type=str, default=signal_type)
    parser.add_argument("--signal_nature", type=str, default=signal_nature)
    parser.add_argument("--eta", type=float, default=eta)
    parser.add_argument("--bias", type=float, default=bias)
    parser.add_argument("--sv_noise_var", type=float, default=sv_noise_var)
    parser.add_argument("--doa_gap", type=float, default=10.0)
    if fixed_gap:
        parser.add_argument("--fixed_gap", action="store_true", default=True, help="Using exact given gap distance")
    else:
        parser.add_argument("--fixed_gap", action="store_true", help="Using exact given gap distance")
    parser.add_argument("--rank", type=int, default=rank, help="Truncation rank; default to M")
    parser.add_argument("--max_samples", type=int, default=None, help="Optional cap on number of snapshots per set before averaging")
    parser.add_argument("--save_iterative_data", default=save_iterative_data, help="Also save teacher-forcing iterative residual data for route-A")

    # -------- DoA <-> U alignment at data-gen time --------
    parser.add_argument(
        "--align_doa",
        default=True,
        help=(
            "If set, align DoA order to iter_u_target order during data generation, "
            "and save doas_aligned{suffix}.npy (and optionally steering_vectors_aligned)."
        ),
    )
    parser.add_argument(
        "--save_aligned_steering",
        default=True,
        help="If set (with --align_doa), also save steering_vectors_aligned{suffix}.npy.",
    )
    parser.add_argument(
        "--prefer_clean_steering",
        default=True,
        help=(
            "If set (with --align_doa), prefer steering_vectors_clean{suffix}.npy for alignment when available. "
            "This is recommended when you suspect noisy steering mismatch."
        ),
    )
    return parser

def main():
    args = _build_arg_parser(N=8, M=2, rank=2, T=2, snr=5.0, signal_type="NarrowBand", signal_nature="coherent", eta=0.0, bias=0.0, sv_noise_var=0.0, save_iterative_data=True,fixed_gap=False).parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)

    params = _build_params(
        N=args.N,
        M=args.M,
        T=args.T,
        snr=args.snr,
        signal_type=args.signal_type,
        signal_nature=args.signal_nature,
        eta=args.eta,
        bias=args.bias,
        sv_noise_var=args.sv_noise_var,
        doa_gap=args.doa_gap,
        fixed_gap=args.fixed_gap,
    )
    suffix = _build_suffix(params, args.T)

    covs_noisy = load_covariances(input_dir, suffix, clean=False)
    covs_clean = load_covariances(input_dir, suffix, clean=True)
    # shape: (num_sets, T, N, N)
    if args.max_samples is not None:
        covs_noisy = covs_noisy[:, : args.max_samples]
        covs_clean = covs_clean[:, : args.max_samples]
    rank_dim = args.rank if args.rank is not None else args.M

    print(
        f"Processing noisy covariances{suffix}.npy (H) & clean covariances_clean{suffix}.npy (U/S/Vh) -> rank_dim={rank_dim}, num_sets={covs_noisy.shape[0]}, T={covs_noisy.shape[1]}"
    )
    U_path, S_path, Vh_path, H_path = svd_truncate_mean(
        covs_noisy, covs_clean, rank=rank_dim, out_dir=output_dir, suffix=suffix
    )

    if args.save_iterative_data:
        generate_iterative_teacher_data(
            covs_noisy=covs_noisy,
            covs_clean=covs_clean,
            rank=rank_dim,
            out_dir=output_dir,
            suffix=suffix,
        )

        # Align doa order to iter_u_target order at DATA-GEN time (so training stays fast)
        signal_type_l = str(args.signal_type).lower()
        is_broadband = signal_type_l.startswith("broadband")
        align_doa_enabled = _as_bool(getattr(args, "align_doa", False))
        prefer_clean_steering = _as_bool(getattr(args, "prefer_clean_steering", False))
        save_aligned_steering = _as_bool(getattr(args, "save_aligned_steering", False))

        if align_doa_enabled and is_broadband:
            print("[INFO] signal_type=Broadband: skip DoA/steering alignment in cov_svd_processing.")
        elif align_doa_enabled:
            try:
                doa_out, sv_out = align_doa_to_u_targets(
                    generated_dir=input_dir,
                    processed_dir=output_dir,
                    suffix=suffix,
                    rank=rank_dim,
                    prefer_clean_steering=prefer_clean_steering,
                    save_reordered_steering=save_aligned_steering,
                )
                print(f"Saved aligned DoAs to: {doa_out}")
                if sv_out is not None:
                    print(f"Saved aligned steering vectors to: {sv_out}")
            except FileNotFoundError as e:
                # For some datasets, steering/doa files might not exist (legacy). Keep pipeline running.
                print(f"[WARN] Skip DoA alignment because a required file is missing: {e}")

    # 读取回数据用于 validate（使用 mmap 模式以节省内存）
    U_mm = np.load(U_path, mmap_mode="r")
    S_mm = np.load(S_path, mmap_mode="r")
    Vh_mm = np.load(Vh_path, mmap_mode="r")
    H_mm = np.load(H_path, mmap_mode="r")
    validate(
        path_dir=output_dir,
        N=args.N,
        M=args.M,
        T=args.T,
        snr=args.snr,
        signal_type=args.signal_type,
        signal_nature=args.signal_nature,
        eta=args.eta,
        bias=args.bias,
        sv_noise_var=args.sv_noise_var,
        doa_gap=args.doa_gap,
        fixed_gap=args.fixed_gap,
    )

if __name__ == "__main__":
    main()