# 用于训练models.model的模型

import os
# Must be set before importing torch / numpy-linked OpenMP runtimes on Windows.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
import time
import math
import torch
import argparse
import numpy as np
from music_method import music_rmse_deg
from models.model_副本 import SVDNet
try:
    from ptflops import get_model_complexity_info
except ModuleNotFoundError:
    get_model_complexity_info = None
from src.system_model import SystemModelParams
from src.data_handler import set_dataset_filename
from torch.utils.data import TensorDataset, DataLoader, random_split
from models.lossfunction import floss, get_scheduler
from models.lossfunction import PeriodicPermutationDoALoss
from models.model_副本 import diag_whiten_hermitian, apply_fba_ri

def _build_params(
    N: int,
    M: int,
    T: int,
    snr: float,
    signal_type: str,
    signal_nature: str,
    eta: float,
    bias: float,
    sv_noise_var: float,
    doa_gap: float = 15.0,
) -> SystemModelParams:
    """Create SystemModelParams with provided fields."""

    return (
        SystemModelParams()
        .set_parameter("N", N)
        .set_parameter("M", M)
        .set_parameter("T", T)
        .set_parameter("snr", snr)
        .set_parameter("signal_type", signal_type)
        .set_parameter("signal_nature", signal_nature)
        .set_parameter("eta", eta)
        .set_parameter("bias", bias)
        .set_parameter("sv_noise_var", sv_noise_var)
        .set_parameter("doa_gap", doa_gap)
    )

def _flat_grad_fill_none(grads, params):
    vec = []
    for g, p in zip(grads, params):
        if g is None:
            vec.append(torch.zeros_like(p).reshape(-1))
        else:
            vec.append(g.reshape(-1))
    return torch.cat(vec)

def _get_shared_params(model, scope="backbone"):
    # 你想验证“共享部分”是否冲突：通常选 backbone + u_head
    if scope == "all":
        return [p for p in model.parameters() if p.requires_grad]
    # backbone: freq_gate, input_proj, blocks, norm, u_head（不含 doa_u_*）
    names = ["freq_gate", "input_proj", "blocks", "norm", "u_head"]
    params = []
    for n in names:
        m = getattr(model, n, None)
        if m is None:
            continue
        params += [p for p in m.parameters() if p.requires_grad]
    return params


def _build_suffix(params: SystemModelParams, samples_size: int) -> str:
    """Suffix consistent with dataset naming (no .h5)."""

    return set_dataset_filename(params, samples_size).replace(".h5", "")


# 要修改用于训练的进行数据，就在这里修改即可
def build_arg_parser_data(phase = 1, tf_schedule = "none", freeze_mode = "none", freeze_spectral = False, grad_diag = False, lambda_dir = 1.0, lambda_doa = 0.0, lambda_fft_recon = 0.2, lambda_phase_recon = 0.2, N = 8, M = 3, rank = 2, T = 100, snr = 30, signal_type = "NarrowBand", signal_nature = "non-coherent", eta = 0.0, bias = 0.0, sv_noise_var = 0.0, doa_gap = 15.0, train_ratio = 0.8) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="SVD-truncate covariance matrices generated by f_gendata.py")
    parser.add_argument("--input_dir", type=str, default="datasets/generated_snapshots", help="Folder containing covariances*.npy")
    parser.add_argument("--output_dir", type=str, default="datasets/processed_cov_svd", help="Folder to save truncated SVD outputs")
    parser.add_argument("--N", type=int, default=N)
    parser.add_argument("--M", type=int, default=M)
    parser.add_argument("--rank", type=int, default=rank)
    parser.add_argument("--T", type=int, default=T)
    parser.add_argument("--snr", type=float, default=snr)
    parser.add_argument("--signal_type", type=str, default=signal_type)
    parser.add_argument("--signal_nature", type=str, default=signal_nature)
    parser.add_argument("--eta", type=float, default=eta)
    parser.add_argument("--bias", type=float, default=bias)
    parser.add_argument("--sv_noise_var", type=float, default=sv_noise_var)
    parser.add_argument("--doa_gap", type=float, default=doa_gap)
    parser.add_argument("--max_samples", type=int, default=None, help="Optional cap on number of snapshots to process (for quick tests)")
    parser.add_argument("--train_ratio", type=float, default=train_ratio, help="Portion of data used for training (0,1]")
    parser.add_argument(
        "--split_seed",
        type=int,
        default=42,
        help="Random seed for train/val split (random_split). Use -1 for non-deterministic split.",
    )
    parser.add_argument("--lambda_dir", type=float, default=lambda_dir)
    parser.add_argument(
        "--dir_mode",
        type=str,
        default="subspace",
        choices=["vector", "subspace"],
        help="Direction/subspace loss mode for U: vector=phase-invariant cosine; subspace=projection loss (rotation+perm invariant)",
    )
    # -------- Phase-2 (shape-A) options --------
    parser.add_argument("--phase", type=int, default=phase, choices=[1, 2], help="Training phase: 1=teacher-forcing single-step; 2=closed-loop residual fine-tune (shape-A)")
    parser.add_argument("--pretrained_path", type=str, default=None, help="Phase-2: path to phase-1 weights. Default: datasets/weights/model{suffix}/model_trained.pth")
    parser.add_argument("--mix_teacher_forcing", type=float, default=0.5, help="Phase-2: probability of using teacher-forcing residual per step (0..1)")
    parser.add_argument("--tf_schedule", type=str, default=tf_schedule, choices=["none", "linear"], help="Phase-2: scheduled sampling for teacher forcing prob")
    parser.add_argument("--tf_start", type=float, default=0.5, help="Phase-2: schedule start tf_p")
    parser.add_argument("--tf_end", type=float, default=0.0, help="Phase-2: schedule end tf_p")
    parser.add_argument("--tf_warmup_epochs", type=int, default=30, help="Phase-2: epochs to keep tf_p=tf_start before decay")
    parser.add_argument("--detach_deflation", action="store_true", help="Phase-2: detach deflation projector to stabilize training")
    parser.add_argument("--phase2_lr_scale", type=float, default=0.2, help="Phase-2: lr multiplier relative to base_lr")
    parser.add_argument("--log_interval", type=int, default=50, help="Print detailed logs every N batches (phase-2)")
    # -------- DoA loss options --------
    parser.add_argument("--lambda_doa", type=float, default=lambda_doa, help="Weight for DoA loss (0 disables DoA loss)")
    parser.add_argument("--doa_mode", type=str, default="rmse", choices=["rmse", "mse"], help="DoA loss mode")

    # -------- FFT reconstruction supervision (noisy -> clean FFT spectrum) --------
    parser.add_argument("--lambda_fft_recon", type=float, default=lambda_fft_recon, help="Weight for FFT-spectrum reconstruction loss")
    parser.add_argument("--fft_recon_mode", type=str, default="complex_l1", choices=["complex_l1", "mag_l1", "mag_mse"], help="Mode for FFT recon loss")
    parser.add_argument("--lambda_phase_recon", type=float, default=lambda_phase_recon, help="Weight for Hd phase reconstruction loss (default 0)")
    parser.add_argument(
        "--fft_pool_mode",
        type=str,
        default="avg",
        choices=["avg", "max"],
        help="Pooling mode for FFT recon loss (if applicable)",
    )

    # 梯度测试
    parser.add_argument("--grad_diag", type=bool, default=grad_diag,
                        help="Enable gradient diagnostics for shared params (phase-1)")
    parser.add_argument("--grad_diag_interval", type=int, default=50)
    parser.add_argument("--grad_diag_scope", type=str, default="all",
                        help="Scope of shared params for grad diagnostics: 'backbone' or 'all'")
    # -------- Debug / freezing options --------
    parser.add_argument(
        "--freeze_mode",
        type=str,
        default=freeze_mode,
        choices=["none", "doa_only", "backbone_only", "u_only"],
        help=(
            "Freeze strategy: "
            "'doa_only' trains only DoA head modules; "
            "'backbone_only' trains u_head + DoA head (freezes the rest); "
            "'u_only' trains u_head + backbone (freezes DoA head); "
            "'none' trains all."
        ),
    )
    # -------- Spectral Refinement freeze control --------
    parser.add_argument(
        "--freeze_spectral",
        default=freeze_spectral,
        help="If set, freeze the spectral_refine module weights. If not set, keep it trainable (overrides freeze_mode).",
    )

    # -------- DoA debug / ablation options --------
    parser.add_argument(
        "--doa_input",
        type=str,
        default="pred_u",
        choices=["pred_u", "gt_u", "steering_u"],
        help=(
            "What to feed into DoA head: "
            "pred_u (normal) | gt_u (use dataset u_target) | "
            "steering_u (use steering vector columns as an upper-bound test; requires steering_vectors*.npy)"
        ),
    )
    parser.add_argument(
        "--doa_disable_tanh",
        action="store_true",
        help=(
            "If set, compute theta_deg from sin/cos without tanh/clip compression "
            "(only affects this test script; requires model to expose sin/cos head)."
        ),
    )

    # -------- MUSIC baseline (sanity check on generated covariances) --------
    parser.add_argument(
        "--run_music",
        default=False,
        help="If set, run a MUSIC baseline on covariances*.npy + doas*.npy and print RMSE (deg).",
    )
    parser.add_argument(
        "--music_only",
        action="store_true",
        help="If set, run only MUSIC baseline then exit (useful when torch is not installed).",
    )
    parser.add_argument("--music_max_sets", type=int, default=4000, help="Max sets for MUSIC eval (None for all)")
    parser.add_argument("--music_grid_num", type=int, default=18001, help="Grid points for MUSIC scan over [-90,90]")
    parser.add_argument("--music_d_over_lambda", type=float, default=0.5, help="ULA spacing / wavelength for steering vector")

    # -------- Optional overrides for training schedule / saving --------
    # If left as None, train.py keeps its internal defaults.
    parser.add_argument("--base_lr", type=float, default=None, help="Override base lr (warmup start)")
    parser.add_argument("--max_lr", type=float, default=None, help="Override max lr (warmup end / cosine start)")
    parser.add_argument("--min_lr", type=float, default=None, help="Override min lr (cosine end)")
    parser.add_argument("--warmup", type=int, default=None, help="Override warmup epochs")
    parser.add_argument("--num_epochs", type=int, default=None, help="Override total training epochs")
    parser.add_argument("--num_sched_epochs", type=int, default=None, help="Override scheduler coverage epochs")
    parser.add_argument("--batch_size", type=int, default=None, help="Override batch size")
    parser.add_argument("--weight_decay", type=float, default=None, help="Override weight decay")
    parser.add_argument(
        "--model_tag",
        type=str,
        default=None,
        help="Optional tag appended to saved checkpoint/loss filenames (e.g. stage1/stage2).",
    )
    return parser


def _set_requires_grad(module: torch.nn.Module, flag: bool) -> None:
    for p in module.parameters():
        p.requires_grad = flag


def _apply_freeze_mode(model: torch.nn.Module, freeze_mode: str) -> None:
    """Apply freeze strategy by toggling requires_grad.

    We keep it resilient to naming changes by checking hasattr.
    """
    fm = str(freeze_mode or "none").lower()
    if fm == "none":
        for p in model.parameters():
            p.requires_grad = True
        return

    # start from full freeze
    for p in model.parameters():
        p.requires_grad = False

    # modules that belong to DoA head (current naming)
    doa_names = [
        "doa_u_proj",
        "doa_u_conv",
        "doa_u_pool",
        "doa_u_head",
        "doa_feat_proj",
        "doa_token_to_complex",
        "doa_x_proj",
        "doa_x_conv",
        "doa_x_pool",
        "doa_x_head",
    ]
    for name in doa_names:
        if hasattr(model, name):
            _set_requires_grad(getattr(model, name), True)

    if fm == "doa_only":
        # only DoA head trainable
        pass
    elif fm == "backbone_only":
        # additionally unfreeze u_head (so u can become DoA-friendly)
        if hasattr(model, "u_head"):
            _set_requires_grad(getattr(model, "u_head"), True)
    elif fm == "u_only":
        # 训练 backbone + u_head，冻结 doa head
        for name, p in model.named_parameters():
            if name.startswith("doa_u_"):
                p.requires_grad = False
            else:
                p.requires_grad = True
    else:
        raise ValueError(f"Unknown freeze_mode: {freeze_mode}")

    # keep positional embedding frozen unless explicitly needed
    if hasattr(model, "pos") and isinstance(model.pos, torch.nn.Parameter):
        model.pos.requires_grad = False


def _get_u_for_doa(
    model_out: tuple,
    u_target_ri: torch.Tensor | None,
    doa_input: str,
) -> torch.Tensor:
    """Return complex u vector to be used by DoA head.

    doa_input:
      - 'pred_u': use model output u
      - 'gt_u': use dataset u_target (upper bound test)
            - 'steering_u': use steering vector (selected elsewhere; this helper does NOT handle it)
    """
    mode = str(doa_input or "pred_u").lower()
    u_pred = model_out[0]
    if mode == "pred_u":
        return u_pred
    if mode == "gt_u":
        if u_target_ri is None:
            raise ValueError("doa_input=gt_u but u_target_ri is None")
        return torch.view_as_complex(u_target_ri.to(torch.float32))
    if mode == "steering_u":
        raise ValueError("doa_input=steering_u must be handled by caller with steering vectors")
    raise ValueError(f"Unknown doa_input: {doa_input}")


def _predict_theta_deg_from_u(model: torch.nn.Module, u_complex: torch.Tensor) -> torch.Tensor:
    """Run DoA head using a provided complex u.

    Requires model to implement predict_theta_deg_from_u(u_complex): (B,N) -> (B,)
    """
    if not hasattr(model, "predict_theta_deg_from_u"):
        raise AttributeError(
            "Model does not implement predict_theta_deg_from_u(u). "
            "Please add this helper to models/model.py so train_test.py can run gt_u ablations."
        )
    return model.predict_theta_deg_from_u(u_complex)


def _compute_tf_p(args, epoch: int, total_epochs: int) -> float:
    """Compute teacher-forcing probability for phase2 based on schedule."""
    if getattr(args, "phase", 1) != 2:
        return float(getattr(args, "mix_teacher_forcing", 1.0))

    sched = str(getattr(args, "tf_schedule", "none")).lower()
    if sched == "none":
        return float(max(0.0, min(1.0, getattr(args, "mix_teacher_forcing", 0.5))))

    # linear schedule: keep tf_start for warmup epochs, then linearly to tf_end
    tf_start = float(getattr(args, "tf_start", 1.0))
    tf_end = float(getattr(args, "tf_end", 0.0))
    warm = int(max(0, getattr(args, "tf_warmup_epochs", 0)))

    if epoch < warm:
        tf_p = tf_start
    else:
        denom = max(1, total_epochs - warm - 1)
        t = min(1.0, (epoch - warm) / float(denom))
        tf_p = tf_start + (tf_end - tf_start) * t

    return float(max(0.0, min(1.0, tf_p)))


def _phase_inv_dir_loss_ri(pred_ri: torch.Tensor, target_ri: torch.Tensor, eps: float = 1e-8) -> torch.Tensor:
    """Phase-invariant direction loss for complex vectors in real/imag format.

    pred_ri/target_ri: (B, N, 2)
    return: scalar
    """
    pred = torch.view_as_complex(pred_ri.to(torch.float32))
    target = torch.view_as_complex(target_ri.to(torch.float32))
    ip = torch.sum(torch.conj(target) * pred, dim=-1)
    num = torch.abs(ip)
    den = torch.linalg.norm(pred, dim=-1) * torch.linalg.norm(target, dim=-1)
    return torch.mean(1.0 - num / (den + eps))


def _deflate_with_u(R_ri: torch.Tensor, u_ri: torch.Tensor, eps: float = 1e-8, detach: bool = False) -> torch.Tensor:
    """Closed-loop deflation: R <- (I-uu^H) R (I-uu^H), keeping Hermitian.

    R_ri: (B,N,N,2), u_ri: (B,N,2)
    return: (B,N,N,2)
    """
    R = torch.view_as_complex(R_ri.to(torch.float32))
    u = torch.view_as_complex(u_ri.to(torch.float32))
    u = u / (torch.linalg.norm(u, dim=1, keepdim=True) + eps)
    B, N, _ = R.shape
    I = torch.eye(N, device=R.device, dtype=R.dtype).unsqueeze(0)
    u_col = u.unsqueeze(-1)
    P = u_col @ u_col.conj().transpose(-2, -1)
    P_perp = I - P
    if detach:
        P_perp = P_perp.detach()
    R2 = P_perp @ R @ P_perp
    R2 = 0.5 * (R2 + R2.conj().transpose(-2, -1))
    return torch.view_as_real(R2)

def _build_criterion(epoch_id: int, R: int):
    """Create loss with existing weights; keep previous hyper-weights."""
    # NOTE: DoA loss (lambda_doa) is configured in main() so this stays minimal.
    return floss(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, lambda_doa=0.0, R=R, dir_mode="vector")


def train_one_epoch(model, data_loader, optimizer, device, epoch_id: int, R: int, total_epochs: int, criterion: floss = None, args_data = None):
    model.train()
    criterion = (criterion or _build_criterion(epoch_id, R)).to(device)

    epoch_loss = 0.0
    dir_loss = 0.0
    mse_loss = 0.0
    recon_loss_epoch = 0.0
    doa_loss_epoch = 0.0
    fft_recon_loss_epoch = 0.0
    phase_recon_loss_epoch = 0.0

    k = 0
    for batch in data_loader:
        # Supports optional clean cov + doa targets:
        #   (inputs, U, S, Vh)
        #   (inputs, clean_inputs, U, S, Vh)
        #   (+ doa_gt_rad)
        #   (+ u_steer_ri)
        clean_inputs = None
        doa_gt_rad = None
        u_steer_ri = None

        if len(batch) >= 5:
            # Heuristic: if 2nd tensor looks like covariance, treat it as clean input.
            # phase-1 clean input shape: (B, N, N, 2)
            # phase-2 (if ever used):     (B, M, N, N, 2)
            if (
                isinstance(batch[1], torch.Tensor)
                and batch[1].dim() in (4, 5)
                and batch[1].size(-1) == 2
                and batch[1].size(-2) == batch[1].size(-3)
            ):
                inputs = batch[0]
                clean_inputs = batch[1]
                U_targets, S_targets, Vh_targets = batch[2], batch[3], batch[4]
                rest = batch[5:]
            else:
                inputs = batch[0]
                U_targets, S_targets, Vh_targets = batch[1], batch[2], batch[3]
                rest = batch[4:]
            if len(rest) >= 1:
                doa_gt_rad = rest[0]
            if len(rest) >= 2:
                u_steer_ri = rest[1]
        else:
            inputs, U_targets, S_targets, Vh_targets = batch
        inputs = inputs.to(device)
        U_targets = U_targets.to(device)
        S_targets = S_targets.to(device)
        Vh_targets = Vh_targets.to(device)
        if clean_inputs is not None:
            clean_inputs = clean_inputs.to(device)
        if doa_gt_rad is not None:
            doa_gt_rad = doa_gt_rad.to(device).to(torch.float32)
        if u_steer_ri is not None:
            u_steer_ri = u_steer_ri.to(device).to(torch.float32)

        # Optional debug print/check for U_targets compatibility when switching dir_mode.
        if getattr(args_data, "grad_diag", False) and (k == 0) and getattr(args_data, "dir_mode", "vector") == "subspace":
            # Expect (B,M,r,2) or (B,M,r) complex
            if U_targets.dim() not in (3, 4):
                raise ValueError(f"dir_mode=subspace expects U_targets dim 3 or 4, got {tuple(U_targets.shape)}")

        optimizer.zero_grad()

        want_fft_recon = float(getattr(criterion, "lambda_fft_recon", 0.0)) > 0
        want_phase_recon = float(getattr(criterion, "lambda_phase_recon", 0.0)) > 0
        want_aux = want_fft_recon or want_phase_recon
        if want_aux:
            if clean_inputs is None:
                raise ValueError("lambda_fft_recon>0 or lambda_phase_recon>0 but dataloader did not provide clean_inputs")
            out = model(inputs, return_aux=True)
        else:
            out = model(inputs)

        U, S, V = out[0], out[1], out[2]
        # theta_deg may be based on pred_u; we optionally recompute from chosen u input
        theta_deg = out[3] if len(out) > 3 else None

        aux = None
        if want_aux:
            aux = out[4]

        # DoA loss (phase-1): single-source label (B,) -> (B,1) for PeriodicPermutationDoALoss
        doa_pred_rad = None
        doa_gt_rad_use = None
        if getattr(criterion, "lambda_doa", 0.0) > 0:
            if doa_gt_rad is None:
                raise ValueError("lambda_doa>0 but dataloader did not provide doa_gt (radians)")

            # If test script attaches doa_input on criterion, use it to optionally feed alternative u.
            doa_input = str(getattr(criterion, "doa_input", "pred_u")).lower()
            theta_deg_use = theta_deg
            if doa_input == "gt_u":
                u_for_doa = _get_u_for_doa(out, U_targets, doa_input=doa_input)
                theta_deg_use = _predict_theta_deg_from_u(model, u_for_doa)
            elif doa_input == "steering_u":
                if u_steer_ri is None:
                    raise ValueError("doa_input=steering_u but dataloader did not provide u_steer_ri")
                u_for_doa = torch.view_as_complex(u_steer_ri)
                theta_deg_use = _predict_theta_deg_from_u(model, u_for_doa)
            if theta_deg_use is None:
                raise ValueError("lambda_doa>0 but theta_deg is None")
            # model outputs theta in degrees; loss expects radians
            if theta_deg_use.dim() == 1:
                doa_pred_rad = (theta_deg_use.view(-1, 1) * (math.pi / 180.0)).to(torch.float32)
            else:
                doa_pred_rad = (theta_deg_use * (math.pi / 180.0)).to(torch.float32)
            # IMPORTANT: doas*.npy from f_gendata.py are already radians
            doa_gt_rad_use = doa_gt_rad.to(torch.float32)
            if doa_gt_rad_use.dim() == 1:
                doa_gt_rad_use = doa_gt_rad_use.view(-1, 1)

        # Build FFT/Phase recon targets if requested
        fft_pred = None
        fft_target = None
        hd_pred = None
        hd_target = None

        if want_aux:
            # Common normalization for targets
            # Target: clean cov -> (fro-norm) -> (diag whiten if enabled)
            clean_norm, _ = model.frobenius_norm_normalize(clean_inputs)
            clean_c = torch.view_as_complex(clean_norm.to(torch.float32))
            if bool(getattr(model, "use_diag_whiten", False)):
                clean_c = diag_whiten_hermitian(clean_c)
            if bool(getattr(model, "use_fba", False)):
                clean_c_ri = torch.view_as_real(clean_c)  # (B,N,N,2)
                clean_c_ri = clean_c_ri.permute(0, 3, 1, 2).contiguous()  # (B,2,N,N)
                clean_c = torch.view_as_complex(
                    apply_fba_ri(clean_c_ri).permute(0, 2, 3, 1).contiguous()
                )

            if want_fft_recon:
                # Prediction: Hf_post from model (after spectral_refine)
                fft_pred = aux["Hf_post"]
                fft_target = torch.fft.fft2(clean_c, norm="ortho")
            
            if want_phase_recon:
                # Prediction: Hd_refined from model (after spatial_refine)
                hd_pred = aux["Hd_refined"]
                # Target: clean spatial covariance
                hd_target = clean_c

        loss, U_dir, _, U_mse, _, S_mse, recon_loss, _doa_loss, _fft_recon_loss, _phase_recon_loss = criterion(
            U_targets,
            S_targets,
            Vh_targets,
            U,
            S,
            V,
            epoch_id=epoch_id,
            doa_pred_rad=doa_pred_rad,
            doa_gt_rad=doa_gt_rad_use,
            fft_pred=fft_pred,
            fft_target=fft_target,
            hd_pred=hd_pred,
            hd_target=hd_target,
        )

        # 测试loss梯度情况
        if getattr(args_data, "grad_diag", False) and (k % getattr(args_data, "grad_diag_interval", 50) == 0):
            shared_params = _get_shared_params(model, scope=args_data.grad_diag_scope)

            # 1) 拆出 dir / doa 两部分标量
            # 你的 floss 已经返回 U_dir 和 doa_loss：doa_loss 是最后一个返回值 :contentReference[oaicite:5]{index=5}
            dir_scalar = U_dir  # 或者你也可以用 total 中 lambda1*U_dir 的“加权版”
            doa_scalar = _doa_loss  # tensor

            g_dir = torch.autograd.grad(dir_scalar, shared_params, retain_graph=True, allow_unused=True)
            g_doa = torch.autograd.grad(doa_scalar, shared_params, retain_graph=True, allow_unused=True)

            v_dir = _flat_grad_fill_none(g_dir, shared_params)
            v_doa = _flat_grad_fill_none(g_doa, shared_params)

            if v_dir is not None and v_doa is not None:
                cos = torch.dot(v_dir, v_doa) / (v_dir.norm() * v_doa.norm() + 1e-12)
                ratio = v_doa.norm() / (v_dir.norm() + 1e-12)
                print(f"[grad] cos(g_dir,g_doa)={cos.item():+.4f} | ||g_doa||/||g_dir||={ratio.item():.4f}")
                # print("dir None:", sum(g is None for g in g_dir), "/", len(g_dir),
                #       "doa None:", sum(g is None for g in g_doa), "/", len(g_doa))

        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
        dir_loss += U_dir.item()
        mse_loss += U_mse.item()
        recon_loss_epoch += recon_loss
        # DoA loss is returned as per-sample batch-mean (see models/lossfunction.py).
        # Keep logging/epoch stats in the same per-sample scale.
        try:
            doa_loss_epoch += float(_doa_loss.detach().cpu())
        except Exception:
            doa_loss_epoch += float(_doa_loss)

        try:
            fft_recon_loss_epoch += float(_fft_recon_loss.detach().cpu())
        except Exception:
            fft_recon_loss_epoch += float(_fft_recon_loss)

        try:
            phase_recon_loss_epoch += float(_phase_recon_loss.detach().cpu())
        except Exception:
            phase_recon_loss_epoch += float(_phase_recon_loss)

        if (k + 1) % 50 == 0 or (k + 1) == len(data_loader):
            S_numpy0 = 0.0
            if S is not None:
                S_list_numpy = S.detach().cpu().numpy()
                S_numpy = np.abs(S_list_numpy)
                S_numpy0 = S_numpy[0, 0]

            # DoA loss is already per-sample
            doa_loss_print = float(_doa_loss.detach().cpu()) if hasattr(_doa_loss, "detach") else float(_doa_loss)
            fft_loss_print = float(_fft_recon_loss.detach().cpu()) if hasattr(_fft_recon_loss, "detach") else float(_fft_recon_loss)
            phase_loss_print = float(_phase_recon_loss.detach().cpu()) if hasattr(_phase_recon_loss, "detach") else float(_phase_recon_loss)
            print(
                "Epoch: {}/{}, Batch: {}/{}, Loss: {:.4f}, DoA_loss: {:.6f} rad, U_dir: {:.4f}, U_mse: {:.4f}, S_mse: {:.4f}, recon_loss: {:.4f}, fft_recon: {:.6f}, phase_recon: {:.6f}, S_modelout: {:.4f}, lr: {:.6f}".format(
                    epoch_id + 1,
                    total_epochs,
                    k + 1,
                    len(data_loader),
                    loss.item(),
                    doa_loss_print,
                    U_dir.item(),
                    U_mse.item(),
                    S_mse,
                    recon_loss,
                    fft_loss_print,
                    phase_loss_print,
                    S_numpy0,
                    optimizer.param_groups[0]["lr"],
                )
            )
        k += 1

    num_batches = len(data_loader)
    return (
        epoch_loss / num_batches,
        dir_loss / num_batches,
        mse_loss / num_batches,
        recon_loss_epoch / num_batches,
        doa_loss_epoch / num_batches,
        fft_recon_loss_epoch / num_batches,
        phase_recon_loss_epoch / num_batches,
    )


def train_one_epoch_phase2(
    model,
    data_loader,
    optimizer,
    device,
    epoch_id: int,
    K: int,
    total_epochs: int,
    mix_teacher_forcing: float = 0.5,
    detach_deflation: bool = False,
    log_interval: int = 50,
):
    """Phase-2 (shape-A): closed-loop residual fine-tune.

    Dataset expectation:
      inputs: iter_cov_noisy_step (B,K,N,N,2)
      targets: iter_u_target      (B,K,N,2)

    Training idea:
      For each sample, start from step-0 residual = inputs[:,0].
      At step i:
        - predict u_hat from current residual
        - compute dir loss w.r.t u_gt
        - build next residual by mixing:
            teacher-forcing residual: inputs[:,i+1]
            free-running residual: deflate(current_residual, u_hat)
    """

    model.train()
    K = int(K)
    tf_p = float(max(0.0, min(1.0, mix_teacher_forcing)))

    epoch_loss = 0.0
    step_losses = torch.zeros(K, device=device)
    doa_loss_epoch = 0.0
    num_batches = len(data_loader)

    for batch_idx, batch in enumerate(data_loader):
        # supports optional doa targets: (inputs, U_targets, _, _, doa_gt_rad)
        if len(batch) == 5:
            inputs, U_targets, _, _, doa_gt_rad = batch
        else:
            inputs, U_targets, _, _ = batch
            doa_gt_rad = None
        # inputs: (B,K,N,N,2) ; U_targets: (B,K,N,2)
        inputs = inputs.to(device).to(torch.float32)
        U_targets = U_targets.to(device).to(torch.float32)
        if doa_gt_rad is not None:
            doa_gt_rad = doa_gt_rad.to(device).to(torch.float32)

        optimizer.zero_grad()

        # set-level DoA loss over K steps (permutation-invariant + pi-periodic)
        doa_criterion = PeriodicPermutationDoALoss(mode="rmse").to(device)

        # start from step-0 residual
        R_cur = inputs[:, 0]
        total = 0.0
        step_losses_batch = []
        doa_pred_list = []
        for i in range(K):
            out = model(R_cur)
            u_hat_c = out[0]  # u_hat_c: (B,N) complex
            theta_deg = out[3] if len(out) > 3 else None
            u_hat_ri = torch.view_as_real(u_hat_c)
            loss_i = _phase_inv_dir_loss_ri(u_hat_ri, U_targets[:, i])

            if doa_gt_rad is not None and theta_deg is not None:
                doa_pred_list.append(theta_deg)

            total = total + loss_i
            step_losses[i] += loss_i.detach()
            step_losses_batch.append(loss_i.detach())

            if i < K - 1:
                R_pred_next = _deflate_with_u(R_cur, u_hat_ri, detach=detach_deflation)
                # sample-wise mixing teacher-forcing vs free-running
                if tf_p >= 1.0:
                    R_cur = inputs[:, i + 1]
                elif tf_p <= 0.0:
                    R_cur = R_pred_next
                else:
                    mask = (torch.rand(R_cur.shape[0], device=device) < tf_p).view(-1, 1, 1, 1)
                    R_cur = torch.where(mask, inputs[:, i + 1], R_pred_next)

        # Combine: DoA main loss + subspace auxiliary (dir) loss
        total = total / K
        doa_loss = 0.0
        if doa_gt_rad is not None and len(doa_pred_list) == K:
            doa_pred_deg = torch.stack(doa_pred_list, dim=1)  # (B,K)
            doa_pred_rad = doa_pred_deg * (math.pi / 180.0)
            doa_gt_slice = doa_gt_rad[:, :K]
            doa_loss = doa_criterion(doa_pred_rad, doa_gt_slice)
            # DoA as main task: weight applied via args.lambda_doa passed into this function by main
            # Here we assume caller has attached attributes lambda_doa/lambda_sub onto function via closure.
            lambda_doa = float(getattr(train_one_epoch_phase2, "lambda_doa", 0.0))
            lambda_sub = float(getattr(train_one_epoch_phase2, "lambda_sub", 1.0))
            total = lambda_sub * total + lambda_doa * doa_loss
            doa_loss_epoch += float(doa_loss.detach().cpu())
        total.backward()
        optimizer.step()

        epoch_loss += float(total.detach().cpu())

        if log_interval is not None and int(log_interval) > 0:
            if (batch_idx + 1) % int(log_interval) == 0 or (batch_idx + 1) == num_batches:
                # step-wise batch report
                step_vals = [float(s.detach().cpu()) for s in step_losses_batch]
                step_str = ", ".join([f"s{i+1}={v:.4f}" for i, v in enumerate(step_vals)])
                
                doa_val = float(doa_loss.detach().cpu()) if hasattr(doa_loss, 'detach') else float(doa_loss)
                print(
                    f"[P2][Epoch {epoch_id+1}/{total_epochs}] batch {batch_idx+1}/{num_batches} "
                    f"loss={float(total.detach().cpu()):.4f} | doa={doa_val:.4f} rad ({doa_val*180/math.pi:.2f} deg) "
                    f"(λdoa={float(getattr(train_one_epoch_phase2,'lambda_doa',0.0)):.3f}, λsub={float(getattr(train_one_epoch_phase2,'lambda_sub',1.0)):.3f}) "
                    f"| {step_str} | tf_p={tf_p:.2f} | detach={detach_deflation} | lr={optimizer.param_groups[0]['lr']:.6f}"
                )

    step_losses = (step_losses / max(1, num_batches)).detach().cpu().numpy()
    return epoch_loss / max(1, num_batches), step_losses, (doa_loss_epoch / max(1, num_batches))


@torch.no_grad()
def eval_one_epoch_phase2(
    model,
    data_loader,
    device,
    K: int,
    mix_teacher_forcing: float = 1.0,
    detach_deflation: bool = True,
):
    model.eval()
    K = int(K)
    tf_p = float(max(0.0, min(1.0, mix_teacher_forcing)))

    epoch_loss = 0.0
    step_losses = torch.zeros(K, device=device)
    doa_loss_epoch = 0.0
    num_batches = len(data_loader)
    
    # 验证集也使用相同的 DoA 评估标准
    doa_criterion = PeriodicPermutationDoALoss(mode="rmse").to(device)

    for batch in data_loader:
        if len(batch) == 5:
            inputs, U_targets, _, _, doa_gt_rad = batch
        else:
            inputs, U_targets, _, _ = batch
            doa_gt_rad = None
        inputs = inputs.to(device).to(torch.float32)
        U_targets = U_targets.to(device).to(torch.float32)
        if doa_gt_rad is not None:
            doa_gt_rad = doa_gt_rad.to(device).to(torch.float32)

        R_cur = inputs[:, 0]
        total = 0.0
        doa_pred_list = []

        for i in range(K):
            out = model(R_cur)
            u_hat_c = out[0]
            theta_deg = out[3] if len(out) > 3 else None
            u_hat_ri = torch.view_as_real(u_hat_c)
            loss_i = _phase_inv_dir_loss_ri(u_hat_ri, U_targets[:, i])
            
            if theta_deg is not None:
                doa_pred_list.append(theta_deg)

            total = total + loss_i
            step_losses[i] += loss_i

            if i < K - 1:
                R_pred_next = _deflate_with_u(R_cur, u_hat_ri, detach=detach_deflation)
                if tf_p >= 1.0:
                    R_cur = inputs[:, i + 1]
                elif tf_p <= 0.0:
                    R_cur = R_pred_next
                else:
                    mask = (torch.rand(R_cur.shape[0], device=device) < tf_p).view(-1, 1, 1, 1)
                    R_cur = torch.where(mask, inputs[:, i + 1], R_pred_next)

        total = total / K
        epoch_loss += float(total.detach().cpu())
        
        # 计算 DoA Metric (RMSE deg -> rad for function, but let's log rad or deg. Loss uses rad inputs)
        if doa_gt_rad is not None and len(doa_pred_list) == K:
            doa_pred_deg = torch.stack(doa_pred_list, dim=1)  # (B,K)
            doa_pred_rad = doa_pred_deg * (math.pi / 180.0)
            doa_gt_slice = doa_gt_rad[:, :K]
            doa_val_loss = doa_criterion(doa_pred_rad, doa_gt_slice)
            doa_loss_epoch += float(doa_val_loss.detach().cpu())

    step_losses = (step_losses / max(1, num_batches)).detach().cpu().numpy()
    return epoch_loss / max(1, num_batches), step_losses, (doa_loss_epoch / max(1, num_batches))


@torch.no_grad()
def validate(model, data_loader, device, epoch_id: int, R: int, criterion: floss = None):
    model.eval()
    # IMPORTANT: to validate DoA loss, we must reuse the same criterion config as training
    # (especially lambda_doa/doa_mode). Fallback to default only if not provided.
    if criterion is None:
        criterion = _build_criterion(epoch_id, R)
    criterion = criterion.to(device)

    epoch_loss = 0.0
    dir_loss = 0.0
    mse_loss = 0.0
    recon_loss_epoch = 0.0
    doa_loss_epoch = 0.0
    fft_recon_loss_epoch = 0.0
    phase_recon_loss_epoch = 0.0

    for batch in data_loader:
        # Supports optional clean cov + doa targets (aligned with train_one_epoch)
        clean_inputs = None
        doa_gt_rad = None
        u_steer_ri = None

        if len(batch) >= 5:
            if (
                isinstance(batch[1], torch.Tensor)
                and batch[1].dim() in (4, 5)
                and batch[1].size(-1) == 2
                and batch[1].size(-2) == batch[1].size(-3)
            ):
                inputs = batch[0]
                clean_inputs = batch[1]
                U_targets, S_targets, Vh_targets = batch[2], batch[3], batch[4]
                rest = batch[5:]
            else:
                inputs = batch[0]
                U_targets, S_targets, Vh_targets = batch[1], batch[2], batch[3]
                rest = batch[4:]
            if len(rest) >= 1:
                doa_gt_rad = rest[0]
            if len(rest) >= 2:
                u_steer_ri = rest[1]
        else:
            inputs, U_targets, S_targets, Vh_targets = batch

        inputs = inputs.to(device)
        U_targets = U_targets.to(device)
        S_targets = S_targets.to(device)
        Vh_targets = Vh_targets.to(device)
        if clean_inputs is not None:
            clean_inputs = clean_inputs.to(device)
        if doa_gt_rad is not None:
            doa_gt_rad = doa_gt_rad.to(device).to(torch.float32)
        if u_steer_ri is not None:
            u_steer_ri = u_steer_ri.to(device).to(torch.float32)

        want_fft_recon = float(getattr(criterion, "lambda_fft_recon", 0.0)) > 0
        want_phase_recon = float(getattr(criterion, "lambda_phase_recon", 0.0)) > 0
        want_aux = want_fft_recon or want_phase_recon
        if want_aux:
            if clean_inputs is None:
                raise ValueError("lambda_fft_recon>0 or lambda_phase_recon>0 but dataloader did not provide clean_inputs")
            out = model(inputs, return_aux=True)
        else:
            out = model(inputs)
        U, S, V = out[0], out[1], out[2]
        theta_deg = out[3] if len(out) > 3 else None

        aux = None
        if want_aux:
            aux = out[4]

        doa_pred_rad = None
        doa_gt_rad_use = None
        if getattr(criterion, "lambda_doa", 0.0) > 0:
            if doa_gt_rad is None:
                raise ValueError("lambda_doa>0 but dataloader did not provide doa_gt (radians)")
            doa_input = str(getattr(criterion, "doa_input", "pred_u")).lower()
            theta_deg_use = theta_deg
            if doa_input == "gt_u":
                u_for_doa = _get_u_for_doa(out, U_targets, doa_input=doa_input)
                theta_deg_use = _predict_theta_deg_from_u(model, u_for_doa)
            elif doa_input == "steering_u":
                if u_steer_ri is None:
                    raise ValueError("doa_input=steering_u but dataloader did not provide u_steer_ri")
                u_for_doa = torch.view_as_complex(u_steer_ri)
                theta_deg_use = _predict_theta_deg_from_u(model, u_for_doa)
            if theta_deg_use is None:
                raise ValueError("lambda_doa>0 but theta_deg is None")
            if theta_deg_use.dim() == 1:
                doa_pred_rad = (theta_deg_use.view(-1, 1) * (math.pi / 180.0)).to(torch.float32)
            else:
                doa_pred_rad = (theta_deg_use * (math.pi / 180.0)).to(torch.float32)
            doa_gt_rad_use = doa_gt_rad.to(torch.float32)
            if doa_gt_rad_use.dim() == 1:
                doa_gt_rad_use = doa_gt_rad_use.view(-1, 1)
        fft_pred = None
        fft_target = None
        hd_pred = None
        hd_target = None
        if want_aux:
            clean_norm, _ = model.frobenius_norm_normalize(clean_inputs)
            clean_c = torch.view_as_complex(clean_norm.to(torch.float32))
            if bool(getattr(model, "use_diag_whiten", False)):
                clean_c = diag_whiten_hermitian(clean_c)
            if bool(getattr(model, "use_fba", False)):
                clean_c_ri = torch.view_as_real(clean_c)  # (B,N,N,2)
                clean_c_ri = clean_c_ri.permute(0, 3, 1, 2).contiguous()  # (B,2,N,N)
                clean_c = torch.view_as_complex(
                    apply_fba_ri(clean_c_ri).permute(0, 2, 3, 1).contiguous()
                )

            if want_fft_recon:
                fft_pred = aux["Hf_post"]
                fft_target = torch.fft.fft2(clean_c, norm="ortho")
            if want_phase_recon:
                hd_pred = aux["Hd_refined"]
                hd_target = clean_c

        loss, U_dir, Vh_dir, U_mse, V_mse, S_mse, recon_loss, _doa_loss, _fft_recon_loss, _phase_recon_loss = criterion(
            U_targets, S_targets, Vh_targets, U, S, V, epoch_id=epoch_id,
            doa_pred_rad=doa_pred_rad,
            doa_gt_rad=doa_gt_rad_use,
            fft_pred=fft_pred,
            fft_target=fft_target,
            hd_pred=hd_pred,
            hd_target=hd_target,
        )

        epoch_loss += loss.item()
        dir_loss += U_dir.item()
        mse_loss += U_mse.item()
        recon_loss_epoch += recon_loss
        try:
            doa_loss_epoch += float(_doa_loss.detach().cpu())
        except Exception:
            doa_loss_epoch += float(_doa_loss)
            
        try:
            fft_recon_loss_epoch += float(_fft_recon_loss.detach().cpu())
        except Exception:
            fft_recon_loss_epoch += float(_fft_recon_loss)

        try:
            phase_recon_loss_epoch += float(_phase_recon_loss.detach().cpu())
        except Exception:
            phase_recon_loss_epoch += float(_phase_recon_loss)

    num_batches = len(data_loader)
    return (
        epoch_loss / num_batches,
        dir_loss / num_batches,
        mse_loss / num_batches,
        recon_loss_epoch / num_batches,
        doa_loss_epoch / num_batches,
        fft_recon_loss_epoch / num_batches,
        phase_recon_loss_epoch / num_batches,
    )

def main():
    os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    args_data = build_arg_parser_data(
        phase=1,
        tf_schedule="none",
        freeze_mode="none",
        freeze_spectral=False,
        grad_diag=False,
        lambda_dir=1.0,
        lambda_doa=1.0,
        lambda_fft_recon=1.0,
        lambda_phase_recon=1.0,
        N=8,
        M=2,
        rank=1,
        T=2,
        snr=5,
        signal_type="NarrowBand",
        signal_nature="coherent",
        eta=0.0,
        bias=0.0,
        sv_noise_var=0.0,
        train_ratio=0.8,
    ).parse_args()
    params = _build_params(
        N=args_data.N,
        M=args_data.M,
        T=args_data.T,
        snr=args_data.snr,
        signal_type=args_data.signal_type,
        signal_nature=args_data.signal_nature,
        eta=args_data.eta,
        bias=args_data.bias,
        sv_noise_var=args_data.sv_noise_var,
        doa_gap=args_data.doa_gap,
    )

    # Resolve suffix robustly (SNR formatting may be saved as 7 or 7.0)
    suffix = _build_suffix(params, args_data.T)
    try:
        snr_val = float(args_data.snr)
    except Exception:
        snr_val = None

    if snr_val is not None and float(snr_val).is_integer():
        # Build two candidates: int-like and float-like (7 vs 7.0)
        params_snr_int = _build_params(
            N=args_data.N,
            M=args_data.M,
            T=args_data.T,
            snr=int(snr_val),
            signal_type=args_data.signal_type,
            signal_nature=args_data.signal_nature,
            eta=args_data.eta,
            bias=args_data.bias,
            sv_noise_var=args_data.sv_noise_var,
            doa_gap=args_data.doa_gap,
        )
        params_snr_float = _build_params(
            N=args_data.N,
            M=args_data.M,
            T=args_data.T,
            snr=float(snr_val),
            signal_type=args_data.signal_type,
            signal_nature=args_data.signal_nature,
            eta=args_data.eta,
            bias=args_data.bias,
            sv_noise_var=args_data.sv_noise_var,
            doa_gap=args_data.doa_gap,
        )
        suffix_int = _build_suffix(params_snr_int, args_data.T)
        suffix_float = _build_suffix(params_snr_float, args_data.T)
        if suffix_int != suffix_float:
            cand = [suffix_int, suffix_float]
            found = None
            for s in cand:
                probe = "datasets/processed_cov_svd/" + f"iter_cov_noisy_step{s}.npy"
                if os.path.exists(probe):
                    found = s
                    break
            if found is not None and found != suffix:
                suffix = found
                print(f"[Suffix] Resolved dataset suffix by existing files: {suffix}")

    # load data (phase-1 and phase-2 both use iter teacher data)
    H_tensor_file = "datasets/processed_cov_svd/" + f"iter_cov_noisy_step{suffix}.npy"
    H_clean_file = "datasets/processed_cov_svd/" + f"iter_cov_clean_step{suffix}.npy"
    U_target_file = "datasets/processed_cov_svd/" + f"iter_u_target{suffix}.npy"
    S_target_file = "datasets/processed_cov_svd/" + f"svd_S{suffix}.npy"
    Vh_target_file = "datasets/processed_cov_svd/" + f"svd_Vh{suffix}.npy"
    doa_file = "datasets/generated_snapshots/" + f"doas{suffix}.npy"
    steering_file = "datasets/generated_snapshots/" + f"steering_vectors{suffix}.npy"

    # ---- MUSIC sanity check (covariance -> DoA) ----
    # This uses ONLY numpy and the f_gendata.py outputs. It's helpful to tell whether
    # the covariance itself contains enough information to reach your target accuracy.
    if bool(getattr(args_data, "run_music", False)):
        cov_file = "datasets/generated_snapshots/" + f"covariances{suffix}.npy"
        if os.path.exists(cov_file) and os.path.exists(doa_file):
            max_sets = getattr(args_data, "music_max_sets", 500)
            max_sets = None if (max_sets is None or int(max_sets) <= 0) else int(max_sets)
            grid_num = int(getattr(args_data, "music_grid_num", 721))
            d_over_lambda = float(getattr(args_data, "music_d_over_lambda", 0.5))
            num_sources = int(getattr(args_data, "M", 1))

            rmse_deg_pi = music_rmse_deg(
                cov_file=cov_file,
                doa_file=doa_file,
                num_sources=num_sources,
                max_sets=max_sets,
                grid_min=-90.0,
                grid_max=90.0,
                grid_num=grid_num,
                d_over_lambda=d_over_lambda,
                wrap_period="pi",
            )
            rmse_deg_2pi = music_rmse_deg(
                cov_file=cov_file,
                doa_file=doa_file,
                num_sources=num_sources,
                max_sets=max_sets,
                grid_min=-90.0,
                grid_max=90.0,
                grid_num=grid_num,
                d_over_lambda=d_over_lambda,
                wrap_period="2pi",
            )
            print(
                f"[MUSIC] RMSE(pi-wrap)={rmse_deg_pi:.3f} deg | RMSE(2pi-wrap)={rmse_deg_2pi:.3f} deg "
                f"on covariances (sets={max_sets or 'all'}, grid={grid_num}, M={num_sources}, d/λ={d_over_lambda})"
            )
        else:
            print(f"[MUSIC] skip: missing files: {cov_file} or {doa_file}")
        if bool(getattr(args_data, "music_only", False)):
            return

    H_tensor = torch.tensor(np.load(H_tensor_file), device=device, dtype=torch.float32)
    # 加载干净协方差矩阵 (如果开启了 lambda_fft_recon 或 lambda_phase_recon)
    H_clean = None
    if float(getattr(args_data, "lambda_fft_recon", 0.0)) > 0 or float(getattr(args_data, "lambda_phase_recon", 0.0)) > 0:
        if not os.path.exists(H_clean_file):
            raise FileNotFoundError(f"lambda_fft_recon>0 or lambda_phase_recon>0 but clean cov file not found: {H_clean_file}")
        H_clean = torch.tensor(np.load(H_clean_file), device=device, dtype=torch.float32)
    U_target = torch.tensor(np.load(U_target_file), device=device, dtype=torch.float32)
    # H_tensor1 = torch.tensor(np.load(H_tensor_file1), device=device, dtype=torch.float32)
    # U_target1 = torch.tensor(np.load(U_target_file1), device=device, dtype=torch.float32)
    # S/Vh 在 phase-1 保留占位；phase-2 不用
    S_target = torch.tensor(np.load(S_target_file), device=device, dtype=torch.float32)
    Vh_target = torch.tensor(np.load(Vh_target_file), device=device, dtype=torch.float32)

    doa_gt = None
    if os.path.exists(doa_file):
        doa_gt = torch.tensor(np.load(doa_file), device=device, dtype=torch.float32)

    steering_u_phase1 = None
    if str(getattr(args_data, "doa_input", "pred_u")).lower() == "steering_u":
        if not os.path.exists(steering_file):
            raise FileNotFoundError(
                f"doa_input=steering_u but steering vectors file not found: {steering_file} "
                "(generate it via f_gendata.py first)"
            )
        A = np.load(steering_file)  # NarrowBand: (num_sets,N,Msrc)
        if A.ndim != 3:
            raise ValueError(f"Expect steering_vectors (num_sets,N,Msrc), got shape={A.shape}")

    # 统一实虚为最后一维，保持快拍维度一致
    # H_tensor = torch.stack([H_tensor.real, H_tensor.imag], dim=-1).reshape(-1, args_data.N, args_data.N, 2)            # (T, M, N, N, 2)
    # Phase-1 expects flattened (num_sets*K, N, N, 2) -> single-step
    # Phase-2 expects unflattened (num_sets, K, N, N, 2) -> closed-loop
    H_tensor = H_tensor.reshape(-1, args_data.M, args_data.N, args_data.N, 2)
    if H_clean is not None:
        H_clean = H_clean.reshape(-1, args_data.M, args_data.N, args_data.N, 2)
    U_target = U_target.reshape(-1, args_data.M, args_data.N, 2)
    Vh_target = Vh_target.reshape(-1, args_data.N, 2)                                 # (T*M, N, 2)
    S_target = S_target.reshape(-1, 1)                                     # (T*M, 1)

    # Prepare DoA GT for phase-1/phase-2
    # - generator doas: (num_sets, M_sources)
    # - iter teacher data: first dim = num_sets; step dim = args_data.M
    doa_gt_phase1 = None
    doa_gt_phase2 = None
    if doa_gt is not None:
        num_sets = int(H_tensor.shape[0])
        if int(doa_gt.shape[0]) != num_sets:
            m = min(int(doa_gt.shape[0]), num_sets)
            doa_gt = doa_gt[:m]
            H_tensor = H_tensor[:m]
            U_target = U_target[:m]
        K_steps = int(args_data.M)
        if int(doa_gt.shape[1]) < K_steps:
            raise ValueError(f"doas file provides only {int(doa_gt.shape[1])} sources but K_steps={K_steps}")
        doa_gt_phase2 = doa_gt[:, :K_steps]
        # phase-1 direct multi-source: keep (num_sets, K) when r=K
        # legacy single-source uses flattened shape (num_sets*K,)
        if int(args_data.M) > 1 and int(getattr(args_data, "phase", 1)) == 1:
            doa_gt_phase1 = doa_gt_phase2
        else:
            doa_gt_phase1 = doa_gt_phase2.reshape(-1)

        # steering_u upper bound (phase-1): use the FIRST source steering vector a(theta_0)
        # then repeat per-step because phase-1 dataset is flattened over K_steps.
        if str(getattr(args_data, "doa_input", "pred_u")).lower() == "steering_u":
            # A loaded earlier: (num_sets,N,Msrc)
            if 'A' not in locals():
                raise RuntimeError("Internal: steering file loaded but A not found in locals()")
            if A.shape[0] != num_sets:
                m = min(int(A.shape[0]), int(num_sets))
                A = A[:m]
                # Keep other tensors aligned
                doa_gt = doa_gt[:m]
                H_tensor = H_tensor[:m]
                U_target = U_target[:m]
                num_sets = m
                # recompute phase labels
                doa_gt_phase2 = doa_gt[:, :K_steps]
                doa_gt_phase1 = doa_gt[:, 0].repeat_interleave(K_steps)
            u0 = A[:, :, 0]  # (num_sets,N)
            u0_ri = np.stack([u0.real, u0.imag], axis=-1).astype(np.float32)  # (num_sets,N,2)
            steering_u_phase1 = torch.tensor(u0_ri, device=device, dtype=torch.float32).repeat_interleave(K_steps, dim=0)

    # 创建统一模型
    folder_path = f"datasets/weights/model{suffix}"
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    # direct multi-source: output r=M vectors per sample
    model = SVDNet(M=args_data.M, N=args_data.N, r=args_data.rank, dim=128, depth=4, attn_dim=64, k_len=args_data.N,refine_mode="both").to(device)

    # 打印Flops（可选依赖 ptflops）
    if get_model_complexity_info is not None:
        flops, params = get_model_complexity_info(model, (args_data.N, args_data.N, 2), as_strings=True, print_per_layer_stat=True)
        print(f"Model complexity: {flops} FLOPS")
    else:
        print("ptflops not installed; skip FLOPs report")

    # 优化器参数设置
    weight_decay = float(getattr(args_data, "weight_decay", None) or 1e-4)  # 权重衰减
    batch_size = int(getattr(args_data, "batch_size", None) or 128)  # 每个batch的大小
    load_pretrained_model = False
    if args_data.lambda_doa > 0.0 or args_data.freeze_mode == "doa_only":
        load_pretrained_model = True

    # warmup 后用余弦退火逐步衰减到极低学习率
    if load_pretrained_model:
        base_lr = 2.5e-4  # warmup 起点
        max_lr = 2.5e-4  # warmup 终点 / 余弦起点
        min_lr = 1e-6  # 余弦终点
        warmup = 10
        # 训练模型参数设置
        num_epochs = 100  # 总轮数
        num_sched_epochs = 80  # 学习率调度覆盖全程
    else:
        base_lr = 1e-3  # warmup 起点
        max_lr = 5e-3  # warmup 终点 / 余弦起点
        min_lr = 1e-4  # 余弦终点
        warmup = 30
        # 训练模型参数设置
        num_epochs = 200  # 总轮数
        num_sched_epochs = 180  # 学习率调度覆盖全程

    # Optional overrides (for automation / ablations)
    if getattr(args_data, "base_lr", None) is not None:
        base_lr = float(args_data.base_lr)
    if getattr(args_data, "max_lr", None) is not None:
        max_lr = float(args_data.max_lr)
    if getattr(args_data, "min_lr", None) is not None:
        min_lr = float(args_data.min_lr)
    if getattr(args_data, "warmup", None) is not None:
        warmup = int(args_data.warmup)
    if getattr(args_data, "num_epochs", None) is not None:
        num_epochs = int(args_data.num_epochs)
    if getattr(args_data, "num_sched_epochs", None) is not None:
        num_sched_epochs = int(args_data.num_sched_epochs)
    # Apply freeze mode for ablation experiments
    _apply_freeze_mode(model, getattr(args_data, "freeze_mode", "none"))

    # Explicit control for spectral_refine (separate switch as requested)
    if hasattr(model, "spectral_refine"):
        should_freeze_spectral = bool(getattr(args_data, "freeze_spectral", False))
        # If freeze_spectral is True -> Set requires_grad=False
        # If freeze_spectral is False -> Set requires_grad=True (override freeze_mode if needed)
        # This matches user requirement: "switch closed (False) -> open gradient", "switch open (True) -> freeze weights"
        _set_requires_grad(model.spectral_refine, not should_freeze_spectral)
        state_str = "Frozen" if should_freeze_spectral else "Trainable"
        print(f"Spectral Refinement module is set to: {state_str} (override)")

    # phase-2 use smaller lr to avoid forgetting
    lr_scale = float(args_data.phase2_lr_scale) if args_data.phase == 2 else 1.0
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=base_lr * lr_scale,
        weight_decay=weight_decay,
    )

    # warmup + cosine scheduler
    warmup_epochs = warmup
    scheduler = get_scheduler(
        optimizer,
        warmup_epochs,
        num_sched_epochs,
        base_lr * lr_scale,
        max_lr * lr_scale,
        min_lr * lr_scale,
    )

    # load pre-trained model
    if load_pretrained_model:
        pre_trained_model_path = args_data.pretrained_path or f"datasets/weights/model{suffix}/model_trained.pth"
        if os.path.exists(pre_trained_model_path):
            model.load_state_dict(torch.load(pre_trained_model_path))
            print(f"Pre-trained model loaded from {pre_trained_model_path}")
        else:
            raise FileNotFoundError(f"Phase-2 pretrained weights not found: {pre_trained_model_path}")

    # 创建数据加载器
    if args_data.phase == 1:
        # direct multi-source: use step-0 covariance as input
        H_in = H_tensor[:, 0]
        U_in = U_target.permute(0, 2, 1, 3).contiguous()
        # placeholders for criterion signature (S/Vh losses are weighted 0 by default)
        S_in = torch.zeros((H_in.shape[0], args_data.M), device=device, dtype=torch.float32)
        Vh_in = torch.zeros((H_in.shape[0], args_data.N, args_data.M, 2), device=device, dtype=torch.float32)
        # Optional clean input for FFT reconstruction (aligned with H_in shape)
        H_clean_in = None
        if H_clean is not None:
            H_clean_in = H_clean[:, 0]

        if args_data.lambda_doa > 0:
            if doa_gt_phase1 is None:
                raise FileNotFoundError(f"lambda_doa>0 but DoA file not found: {doa_file}")
            if str(getattr(args_data, "doa_input", "pred_u")).lower() == "steering_u":
                if int(args_data.M) > 1:
                    raise ValueError("doa_input=steering_u is only supported for single-source training")
                if steering_u_phase1 is None:
                    raise ValueError("doa_input=steering_u but steering_u_phase1 is None")
                if H_clean_in is not None:
                    dataset = TensorDataset(H_in, H_clean_in, U_in, S_in, Vh_in, doa_gt_phase1, steering_u_phase1)
                else:
                    dataset = TensorDataset(H_in, U_in, S_in, Vh_in, doa_gt_phase1, steering_u_phase1)
            else:
                if H_clean_in is not None:
                    dataset = TensorDataset(H_in, H_clean_in, U_in, S_in, Vh_in, doa_gt_phase1)
                else:
                    dataset = TensorDataset(H_in, U_in, S_in, Vh_in, doa_gt_phase1)
        else:
            if H_clean_in is not None:
                dataset = TensorDataset(H_in, H_clean_in, U_in, S_in, Vh_in)
            else:
                dataset = TensorDataset(H_in, U_in, S_in, Vh_in)
    else:
        # keep step dimension for phase-2
        # placeholders for dataloader signature
        dummy_S = torch.zeros((H_tensor.shape[0], 1), device=device, dtype=torch.float32)
        dummy_Vh = torch.zeros((H_tensor.shape[0], args_data.N, 2), device=device, dtype=torch.float32)
        if args_data.lambda_doa > 0:
            if doa_gt_phase2 is None:
                raise FileNotFoundError(f"lambda_doa>0 but DoA file not found: {doa_file}")
            dataset = TensorDataset(H_tensor, U_target, dummy_S, dummy_Vh, doa_gt_phase2)
        else:
            dataset = TensorDataset(H_tensor, U_target, dummy_S, dummy_Vh)
    # 设置训练集/测试集比例
    train_ratio = max(0.0, min(1.0, args_data.train_ratio))
    train_size = int(train_ratio * len(dataset))
    test_size = len(dataset) - train_size
    if train_size == 0:
        raise ValueError("train_ratio 太小，导致没有训练样本")
    # 划分（可复现）
    split_seed = int(getattr(args_data, "split_seed", 42))
    split_gen = None if split_seed < 0 else torch.Generator().manual_seed(split_seed)
    train_dataset, test_dataset = random_split(dataset, [train_size, test_size], generator=split_gen)
    if split_seed < 0:
        print(f"Split: train={train_size}, test={test_size} | split_seed=non-deterministic")
    else:
        print(f"Split: train={train_size}, test={test_size} | split_seed={split_seed}")
    # 数据加载器
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False) if test_size > 0 else None

    print("Start training...")
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(
        f"Freeze mode: {getattr(args_data,'freeze_mode','none')} | doa_input: {getattr(args_data,'doa_input','pred_u')} "
        f"| trainable params: {trainable_params}/{total_params}"
    )
    loss_list = []
    val_loss_list = []
    # Save separate DoA loss curves only when enabled.
    doa_loss_list = [] if float(getattr(args_data, "lambda_doa", 0.0)) > 0 else None
    val_doa_loss_list = [] if float(getattr(args_data, "lambda_doa", 0.0)) > 0 else None
    best_model_state = None
    best_loss = np.inf

    for epoch in range(num_epochs):
        model.set_tau_s(epoch_id=epoch)

        tf_p_epoch = _compute_tf_p(args_data, epoch=epoch, total_epochs=num_epochs)

        begin_time = time.time()
        criterion = None
        if args_data.phase == 1:
            # phase-1: enable DoA loss inside floss (single-source)
            criterion = floss(
                lambda1=float(args_data.lambda_dir),
                lambda2=0.0,
                lambda3=0.0,
                lambda4=0.0,
                lambda5=0.0,
                lambda6=0.0,
                lambda_doa=float(args_data.lambda_doa),
                doa_mode=str(args_data.doa_mode),
                dir_mode=str(getattr(args_data, "dir_mode", "vector")),
                R=args_data.rank,
                lambda_fft_recon=float(getattr(args_data, "lambda_fft_recon", 0.0)),
                fft_recon_mode=str(getattr(args_data, "fft_recon_mode", "mag_l1")),
                lambda_phase_recon=float(getattr(args_data, "lambda_phase_recon", 0.0)),
                dir_effective_rank="full",
            ).to(device)
            # attach ablation flags on criterion (keeps train_one_epoch signature unchanged)
            setattr(criterion, "doa_input", str(getattr(args_data, "doa_input", "pred_u")))
            train_loss, train_dir, train_mse, train_recon, train_doa, train_fft_recon, train_phase_recon = train_one_epoch(
                model, train_loader, optimizer, device, epoch, args_data.M, num_epochs, criterion=criterion,
                args_data=args_data,
            )
        else:
            # attach weights (DoA main task + subspace auxiliary) to phase2 trainer
            train_one_epoch_phase2.lambda_doa = float(args_data.lambda_doa)
            train_one_epoch_phase2.lambda_sub = args_data.lambda_dir
            train_loss, step_losses, train_doa = train_one_epoch_phase2(
                model,
                train_loader,
                optimizer,
                device,
                epoch,
                K=args_data.M,
                total_epochs=num_epochs,
                mix_teacher_forcing=tf_p_epoch,
                detach_deflation=args_data.detach_deflation,
                log_interval=args_data.log_interval,
            )
            train_dir = float(np.mean(step_losses))
            train_mse = 0.0
            train_recon = 0.0
            train_fft_recon = 0.0
            train_recon = 0.0

        if epoch < num_sched_epochs:
            scheduler.step()

        val_metrics = None
        if val_loader is not None and len(val_loader) > 0:
            if args_data.phase == 1:
                val_metrics = validate(model, val_loader, device, epoch, args_data.M, criterion=criterion)
            else:
                val_loss, val_steps, val_doa_loss = eval_one_epoch_phase2(
                    model,
                    val_loader,
                    device=device,
                    K=args_data.M,
                    mix_teacher_forcing=1.0,  # val 仍用 teacher residual，指标更可比
                    detach_deflation=True,
                )
                val_metrics = (val_loss, float(np.mean(val_steps)), 0.0, 0.0, val_doa_loss)

        end_time = time.time()
        epoch_time = end_time - begin_time

        loss_list.append(train_loss)
        if doa_loss_list is not None:
            # train_doa is already a scalar (float/tensor); keep per-epoch mean.
            doa_loss_list.append(float(train_doa))
        if val_metrics:
            # phase-1 validate may return:
            #   (loss, dir, mse, recon, doa)
            #   (loss, dir, mse, recon, doa, fft_recon)
            #   (loss, dir, mse, recon, doa, fft_recon, phase_recon)
            # phase-2 validate returns (loss, dir, mse, recon, doa)
            val_phase_recon = 0.0
            if len(val_metrics) == 7:
                val_loss, val_dir, val_mse, val_recon, val_doa, val_fft_recon, val_phase_recon = val_metrics
            elif len(val_metrics) == 6:
                val_loss, val_dir, val_mse, val_recon, val_doa, val_fft_recon = val_metrics
            elif len(val_metrics) == 5:
                val_loss, val_dir, val_mse, val_recon, val_doa = val_metrics
                val_fft_recon = 0.0
            else:
                val_loss, val_dir, val_mse, val_recon = val_metrics
                val_doa = 0.0
                val_fft_recon = 0.0
            val_loss_list.append(val_loss)
            if val_doa_loss_list is not None:
                val_doa_loss_list.append(float(val_doa))

        print(
            f"Epoch {epoch+1}/{num_epochs} | train loss {train_loss:.4f}, doa {float(train_doa):.4f}, dir {train_dir:.4f}, mse {train_mse:.4f}, recon {train_recon:.4f}"
        )
        if args_data.phase == 2:
            print(f"               [P2] tf_p (epoch) = {tf_p_epoch:.3f} | schedule={args_data.tf_schedule} | warmup={args_data.tf_warmup_epochs}")
        if val_metrics:
            print(
                f"               val loss {val_loss:.4f}, doa {float(val_doa):.4f}, dir {val_dir:.4f}, mse {val_mse:.4f}, recon {val_recon:.4f}, fft_recon {val_fft_recon:.4f}, phase_recon {val_phase_recon:.4f}, time {epoch_time:.1f}s"
            )
            if args_data.phase == 2:
                train_steps_str = ", ".join([f"s{i+1}={v:.4f}" for i, v in enumerate(step_losses)])
                val_steps_str = ", ".join([f"s{i+1}={v:.4f}" for i, v in enumerate(val_steps)])
                print(f"               [P2] train step losses: {train_steps_str}")
                print(f"               [P2]   val step losses: {val_steps_str}")
        else:
            print(f"              time {epoch_time:.1f}s (no val set)")
            if args_data.phase == 2:
                train_steps_str = ", ".join([f"s{i+1}={v:.4f}" for i, v in enumerate(step_losses)])
                print(f"               [P2] train step losses: {train_steps_str}")

        metric_for_selection = val_metrics[0] if val_metrics else train_loss
        if metric_for_selection < best_loss:
            best_loss = metric_for_selection
            best_model_state = model.state_dict().copy()
            print("New best model updated")

            # 保存最优模型
            default_tag = "phase2" if args_data.phase == 2 else "phase1"
            tag = str(getattr(args_data, "model_tag", "") or "").strip() or default_tag
            # Keep legacy default name only when user doesn't provide a tag and phase==1
            if args_data.phase == 1 and (getattr(args_data, "model_tag", None) is None):
                model_save_name = "model_trained.pth"
            else:
                model_save_name = f"model_trained_{tag}.pth"
            model_save_path = f"datasets/weights/model{suffix}/{model_save_name}"
            if best_model_state is not None:
                torch.save(best_model_state, model_save_path)
                print(f"Best model saved to {model_save_path}, best metric {best_loss:.4f}")
            else:
                print("Warning: No model was saved")

            # 保存训练/验证 loss 曲线
            loss_file_name = "model_train_loss.txt" if (args_data.phase == 1 and getattr(args_data, "model_tag", None) is None) else f"model_train_loss_{tag}.txt"
            loss_file_path = f"datasets/weights/model{suffix}/{loss_file_name}"
            np.savetxt(loss_file_path, np.array(loss_list), fmt='%.6f')

            # 保存 DoA loss 曲线（仅当 lambda_doa>0 时启用）
            if doa_loss_list is not None:
                doa_loss_file_name = "model_train_doa_loss.txt" if (args_data.phase == 1 and getattr(args_data, "model_tag", None) is None) else f"model_train_doa_loss_{tag}.txt"
                doa_loss_file_path = f"datasets/weights/model{suffix}/{doa_loss_file_name}"
                np.savetxt(doa_loss_file_path, np.array(doa_loss_list), fmt='%.6f')

            if val_loss_list:
                val_loss_file_name = "model_val_loss.txt" if (args_data.phase == 1 and getattr(args_data, "model_tag", None) is None) else f"model_val_loss_{tag}.txt"
                val_loss_file_path = f"datasets/weights/model{suffix}/{val_loss_file_name}"
                np.savetxt(val_loss_file_path, np.array(val_loss_list), fmt='%.6f')
                if val_doa_loss_list is not None:
                    val_doa_loss_file_name = "model_val_doa_loss.txt" if (args_data.phase == 1 and getattr(args_data, "model_tag", None) is None) else f"model_val_doa_loss_{tag}.txt"
                    val_doa_loss_file_path = f"datasets/weights/model{suffix}/{val_doa_loss_file_name}"
                    np.savetxt(val_doa_loss_file_path, np.array(val_doa_loss_list), fmt='%.6f')
                print(f"Training/validation loss saved to {loss_file_path} / {val_loss_file_path}")
            else:
                print(f"Training loss saved to {loss_file_path} (no validation set)")

    print(f"Unified model training completed!")

if __name__ == "__main__":
    main()