"""Training entry point for the DDCR DoA model."""

import os
# Must be set before importing torch / numpy-linked OpenMP runtimes on Windows.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
import time
import math
import torch
import argparse
import numpy as np
from music_method import music_rmse_deg
from models import DDCRNet
try:
    from ptflops import get_model_complexity_info
except ModuleNotFoundError:
    get_model_complexity_info = None
from src.system_model import SystemModelParams
from src.data_handler import set_dataset_filename
from torch.utils.data import TensorDataset, DataLoader, random_split
from models.lossfunction import floss, get_scheduler
from models import diag_whiten_hermitian, apply_fba_ri

def _build_params(
    N: int,
    M: int,
    T: int,
    snr: float,
    signal_type: str,
    signal_nature: str,
    eta: float,
    bias: float,
    sv_noise_var: float,
    doa_gap: float = 15.0,
) -> SystemModelParams:
    """Create SystemModelParams with provided fields."""

    return (
        SystemModelParams()
        .set_parameter("N", N)
        .set_parameter("M", M)
        .set_parameter("T", T)
        .set_parameter("snr", snr)
        .set_parameter("signal_type", signal_type)
        .set_parameter("signal_nature", signal_nature)
        .set_parameter("eta", eta)
        .set_parameter("bias", bias)
        .set_parameter("sv_noise_var", sv_noise_var)
        .set_parameter("doa_gap", doa_gap)
    )

def _flat_grad_fill_none(grads, params):
    vec = []
    for g, p in zip(grads, params):
        if g is None:
            vec.append(torch.zeros_like(p).reshape(-1))
        else:
            vec.append(g.reshape(-1))
    return torch.cat(vec)

def _get_shared_params(model, scope="backbone"):
    # Gradient diagnostics usually inspect the shared representation path.
    if scope == "all":
        return [p for p in model.parameters() if p.requires_grad]
    # Backbone path before the task-specific DoA readout.
    names = ["freq_gate", "input_proj", "blocks", "norm", "u_head"]
    params = []
    for n in names:
        m = getattr(model, n, None)
        if m is None:
            continue
        params += [p for p in m.parameters() if p.requires_grad]
    return params


def _build_suffix(params: SystemModelParams, samples_size: int) -> str:
    """Suffix consistent with dataset naming (no .h5)."""

    return set_dataset_filename(params, samples_size).replace(".h5", "")


# 要修改用于训练的进行数据，就在这里修改即可
def build_arg_parser_data(phase = 1, freeze_mode = "none", freeze_spectral = False, grad_diag = False, lambda_dir = 1.0, lambda_doa = 0.0, lambda_fft_recon = 0.2, lambda_phase_recon = 0.2, N = 8, M = 3, rank = 2, T = 100, snr = 30, signal_type = "NarrowBand", signal_nature = "non-coherent", eta = 0.0, bias = 0.0, sv_noise_var = 0.0, doa_gap = 15.0, train_ratio = 0.8) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="SVD-truncate covariance matrices generated by f_gendata.py")
    parser.add_argument("--input_dir", type=str, default="datasets/generated_snapshots", help="Folder containing covariances*.npy")
    parser.add_argument("--output_dir", type=str, default="datasets/processed_cov_svd", help="Folder to save truncated SVD outputs")
    parser.add_argument("--N", type=int, default=N)
    parser.add_argument("--M", type=int, default=M)
    parser.add_argument("--rank", type=int, default=rank)
    parser.add_argument("--T", type=int, default=T)
    parser.add_argument("--snr", type=float, default=snr)
    parser.add_argument("--signal_type", type=str, default=signal_type)
    parser.add_argument("--signal_nature", type=str, default=signal_nature)
    parser.add_argument("--eta", type=float, default=eta)
    parser.add_argument("--bias", type=float, default=bias)
    parser.add_argument("--sv_noise_var", type=float, default=sv_noise_var)
    parser.add_argument("--doa_gap", type=float, default=doa_gap)
    parser.add_argument("--max_samples", type=int, default=None, help="Optional cap on number of snapshots to process (for quick tests)")
    parser.add_argument("--train_ratio", type=float, default=train_ratio, help="Portion of data used for training (0,1]")
    parser.add_argument(
        "--split_seed",
        type=int,
        default=42,
        help="Random seed for train/val split (random_split). Use -1 for non-deterministic split.",
    )
    parser.add_argument("--lambda_dir", type=float, default=lambda_dir)
    parser.add_argument(
        "--dir_mode",
        type=str,
        default="subspace",
        choices=["vector", "subspace"],
        help="Direction/subspace loss mode for U: vector=phase-invariant cosine; subspace=projection loss (rotation+perm invariant)",
    )
    # Kept for compatibility with existing launch scripts.
    parser.add_argument("--phase", type=int, default=phase, choices=[1], help="Compatibility flag; only phase=1 is supported.")
    parser.add_argument("--pretrained_path", type=str, default=None, help="Optional checkpoint path for fine-tuning.")
    parser.add_argument("--log_interval", type=int, default=50, help="Print detailed logs every N batches.")
    # -------- DoA loss options --------
    parser.add_argument("--lambda_doa", type=float, default=lambda_doa, help="Weight for DoA loss (0 disables DoA loss)")
    parser.add_argument("--doa_mode", type=str, default="rmse", choices=["rmse", "mse"], help="DoA loss mode")

    # -------- FFT reconstruction supervision (noisy -> clean FFT spectrum) --------
    parser.add_argument("--lambda_fft_recon", type=float, default=lambda_fft_recon, help="Weight for FFT-spectrum reconstruction loss")
    parser.add_argument("--fft_recon_mode", type=str, default="complex_l1", choices=["complex_l1", "mag_l1", "mag_mse"], help="Mode for FFT recon loss")
    parser.add_argument("--lambda_phase_recon", type=float, default=lambda_phase_recon, help="Weight for Hd phase reconstruction loss (default 0)")
    parser.add_argument(
        "--fft_pool_mode",
        type=str,
        default="avg",
        choices=["avg", "max"],
        help="Pooling mode for FFT recon loss (if applicable)",
    )

    # 梯度测试
    parser.add_argument("--grad_diag", type=bool, default=grad_diag,
                        help="Enable gradient diagnostics for shared params (phase-1)")
    parser.add_argument("--grad_diag_interval", type=int, default=50)
    parser.add_argument("--grad_diag_scope", type=str, default="all",
                        help="Scope of shared params for grad diagnostics: 'backbone' or 'all'")
    # -------- Debug / freezing options --------
    parser.add_argument(
        "--freeze_mode",
        type=str,
        default=freeze_mode,
        choices=["none", "doa_only", "backbone_only", "u_only"],
        help=(
            "Freeze strategy: "
            "'doa_only' trains only DoA head modules; "
            "'backbone_only' trains u_head + DoA head (freezes the rest); "
            "'u_only' trains u_head + backbone (freezes DoA head); "
            "'none' trains all."
        ),
    )
    # -------- Spectral Refinement freeze control --------
    parser.add_argument(
        "--freeze_spectral",
        default=freeze_spectral,
        help="If set, freeze the spectral_refine module weights. If not set, keep it trainable (overrides freeze_mode).",
    )

    # -------- MUSIC baseline (sanity check on generated covariances) --------
    parser.add_argument(
        "--run_music",
        default=False,
        help="If set, run a MUSIC baseline on covariances*.npy + doas*.npy and print RMSE (deg).",
    )
    parser.add_argument(
        "--music_only",
        action="store_true",
        help="If set, run only MUSIC baseline then exit (useful when torch is not installed).",
    )
    parser.add_argument("--music_max_sets", type=int, default=4000, help="Max sets for MUSIC eval (None for all)")
    parser.add_argument("--music_grid_num", type=int, default=18001, help="Grid points for MUSIC scan over [-90,90]")
    parser.add_argument("--music_d_over_lambda", type=float, default=0.5, help="ULA spacing / wavelength for steering vector")

    # -------- Optional overrides for training schedule / saving --------
    # If left as None, train.py keeps its internal defaults.
    parser.add_argument("--base_lr", type=float, default=None, help="Override base lr (warmup start)")
    parser.add_argument("--max_lr", type=float, default=None, help="Override max lr (warmup end / cosine start)")
    parser.add_argument("--min_lr", type=float, default=None, help="Override min lr (cosine end)")
    parser.add_argument("--warmup", type=int, default=None, help="Override warmup epochs")
    parser.add_argument("--num_epochs", type=int, default=None, help="Override total training epochs")
    parser.add_argument("--num_sched_epochs", type=int, default=None, help="Override scheduler coverage epochs")
    parser.add_argument("--batch_size", type=int, default=None, help="Override batch size")
    parser.add_argument("--weight_decay", type=float, default=None, help="Override weight decay")
    parser.add_argument(
        "--model_tag",
        type=str,
        default=None,
        help="Optional tag appended to saved checkpoint/loss filenames (e.g. stage1/stage2).",
    )
    return parser


def _set_requires_grad(module: torch.nn.Module, flag: bool) -> None:
    for p in module.parameters():
        p.requires_grad = flag


def _apply_freeze_mode(model: torch.nn.Module, freeze_mode: str) -> None:
    """Apply freeze strategy by toggling requires_grad.

    We keep it resilient to naming changes by checking hasattr.
    """
    fm = str(freeze_mode or "none").lower()
    if fm == "none":
        for p in model.parameters():
            p.requires_grad = True
        return

    # start from full freeze
    for p in model.parameters():
        p.requires_grad = False

    # modules that belong to DoA head (current naming)
    doa_names = [
        "doa_feat_proj",
        "doa_token_to_complex",
        "doa_x_proj",
        "doa_x_conv",
        "doa_x_pool",
        "doa_x_head",
    ]
    for name in doa_names:
        if hasattr(model, name):
            _set_requires_grad(getattr(model, name), True)

    if fm == "doa_only":
        # only DoA head trainable
        pass
    elif fm == "backbone_only":
        # additionally unfreeze u_head (so u can become DoA-friendly)
        if hasattr(model, "u_head"):
            _set_requires_grad(getattr(model, "u_head"), True)
    elif fm == "u_only":
        # 训练 backbone + u_head，冻结 doa head
        for name, p in model.named_parameters():
            if name.startswith("doa_"):
                p.requires_grad = False
            else:
                p.requires_grad = True
    else:
        raise ValueError(f"Unknown freeze_mode: {freeze_mode}")

    # keep positional embedding frozen unless explicitly needed
    if hasattr(model, "pos") and isinstance(model.pos, torch.nn.Parameter):
        model.pos.requires_grad = False


def _build_criterion(epoch_id: int, R: int):
    """Create loss with existing weights; keep previous hyper-weights."""
    # NOTE: DoA loss (lambda_doa) is configured in main() so this stays minimal.
    return floss(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, lambda_doa=0.0, R=R, dir_mode="vector")


def train_one_epoch(model, data_loader, optimizer, device, epoch_id: int, R: int, total_epochs: int, criterion: floss = None, args_data = None):
    model.train()
    criterion = (criterion or _build_criterion(epoch_id, R)).to(device)

    epoch_loss = 0.0
    dir_loss = 0.0
    mse_loss = 0.0
    recon_loss_epoch = 0.0
    doa_loss_epoch = 0.0
    fft_recon_loss_epoch = 0.0
    phase_recon_loss_epoch = 0.0

    k = 0
    for batch in data_loader:
        # Supports optional clean cov + doa targets:
        #   (inputs, U, S, Vh)
        #   (inputs, clean_inputs, U, S, Vh)
        #   (+ doa_gt_rad)
        clean_inputs = None
        doa_gt_rad = None

        if len(batch) >= 5:
            # Heuristic: if 2nd tensor looks like covariance, treat it as clean input.
            # phase-1 clean input shape: (B, N, N, 2)
            if (
                isinstance(batch[1], torch.Tensor)
                and batch[1].dim() in (4, 5)
                and batch[1].size(-1) == 2
                and batch[1].size(-2) == batch[1].size(-3)
            ):
                inputs = batch[0]
                clean_inputs = batch[1]
                U_targets, S_targets, Vh_targets = batch[2], batch[3], batch[4]
                rest = batch[5:]
            else:
                inputs = batch[0]
                U_targets, S_targets, Vh_targets = batch[1], batch[2], batch[3]
                rest = batch[4:]
            if len(rest) >= 1:
                doa_gt_rad = rest[0]
        else:
            inputs, U_targets, S_targets, Vh_targets = batch
        inputs = inputs.to(device)
        U_targets = U_targets.to(device)
        S_targets = S_targets.to(device)
        Vh_targets = Vh_targets.to(device)
        if clean_inputs is not None:
            clean_inputs = clean_inputs.to(device)
        if doa_gt_rad is not None:
            doa_gt_rad = doa_gt_rad.to(device).to(torch.float32)

        # Optional debug print/check for U_targets compatibility when switching dir_mode.
        if getattr(args_data, "grad_diag", False) and (k == 0) and getattr(args_data, "dir_mode", "vector") == "subspace":
            # Expect (B,M,r,2) or (B,M,r) complex
            if U_targets.dim() not in (3, 4):
                raise ValueError(f"dir_mode=subspace expects U_targets dim 3 or 4, got {tuple(U_targets.shape)}")

        optimizer.zero_grad()

        want_fft_recon = float(getattr(criterion, "lambda_fft_recon", 0.0)) > 0
        want_phase_recon = float(getattr(criterion, "lambda_phase_recon", 0.0)) > 0
        want_aux = want_fft_recon or want_phase_recon
        if want_aux:
            if clean_inputs is None:
                raise ValueError("lambda_fft_recon>0 or lambda_phase_recon>0 but dataloader did not provide clean_inputs")
            out = model(inputs, return_aux=True)
        else:
            out = model(inputs)

        U, S, V = out[0], out[1], out[2]
        # theta_deg is produced directly by the model's DoA head.
        theta_deg = out[3] if len(out) > 3 else None

        aux = None
        if want_aux:
            aux = out[4]

        # DoA loss: align predicted and ground-truth angles in radians.
        doa_pred_rad = None
        doa_gt_rad_use = None
        if getattr(criterion, "lambda_doa", 0.0) > 0:
            if doa_gt_rad is None:
                raise ValueError("lambda_doa>0 but dataloader did not provide doa_gt (radians)")

            if theta_deg is None:
                raise ValueError("lambda_doa>0 but theta_deg is None")
            # model outputs theta in degrees; loss expects radians
            if theta_deg.dim() == 1:
                doa_pred_rad = (theta_deg.view(-1, 1) * (math.pi / 180.0)).to(torch.float32)
            else:
                doa_pred_rad = (theta_deg * (math.pi / 180.0)).to(torch.float32)
            # IMPORTANT: doas*.npy from f_gendata.py are already radians
            doa_gt_rad_use = doa_gt_rad.to(torch.float32)
            if doa_gt_rad_use.dim() == 1:
                doa_gt_rad_use = doa_gt_rad_use.view(-1, 1)

        # Build FFT/Phase recon targets if requested
        fft_pred = None
        fft_target = None
        hd_pred = None
        hd_target = None

        if want_aux:
            # Common normalization for targets
            # Target: clean cov -> (fro-norm) -> (diag whiten if enabled)
            clean_norm, _ = model.frobenius_norm_normalize(clean_inputs)
            clean_c = torch.view_as_complex(clean_norm.to(torch.float32))
            if bool(getattr(model, "use_diag_whiten", False)):
                clean_c = diag_whiten_hermitian(clean_c)
            if bool(getattr(model, "use_fba", False)):
                clean_c_ri = torch.view_as_real(clean_c)  # (B,N,N,2)
                clean_c_ri = clean_c_ri.permute(0, 3, 1, 2).contiguous()  # (B,2,N,N)
                clean_c = torch.view_as_complex(
                    apply_fba_ri(clean_c_ri).permute(0, 2, 3, 1).contiguous()
                )

            if want_fft_recon:
                # Prediction: Hf_post from model (after spectral_refine)
                fft_pred = aux["Hf_post"]
                fft_target = torch.fft.fft2(clean_c, norm="ortho")
            
            if want_phase_recon:
                # Prediction: Hd_refined from model (after spatial_refine)
                hd_pred = aux["Hd_refined"]
                # Target: clean spatial covariance
                hd_target = clean_c

        loss, U_dir, _, U_mse, _, S_mse, recon_loss, _doa_loss, _fft_recon_loss, _phase_recon_loss = criterion(
            U_targets,
            S_targets,
            Vh_targets,
            U,
            S,
            V,
            epoch_id=epoch_id,
            doa_pred_rad=doa_pred_rad,
            doa_gt_rad=doa_gt_rad_use,
            fft_pred=fft_pred,
            fft_target=fft_target,
            hd_pred=hd_pred,
            hd_target=hd_target,
        )

        # 测试loss梯度情况
        if getattr(args_data, "grad_diag", False) and (k % getattr(args_data, "grad_diag_interval", 50) == 0):
            shared_params = _get_shared_params(model, scope=args_data.grad_diag_scope)

            # 1) 拆出 dir / doa 两部分标量
            # 你的 floss 已经返回 U_dir 和 doa_loss：doa_loss 是最后一个返回值 :contentReference[oaicite:5]{index=5}
            dir_scalar = U_dir  # 或者你也可以用 total 中 lambda1*U_dir 的“加权版”
            doa_scalar = _doa_loss  # tensor

            g_dir = torch.autograd.grad(dir_scalar, shared_params, retain_graph=True, allow_unused=True)
            g_doa = torch.autograd.grad(doa_scalar, shared_params, retain_graph=True, allow_unused=True)

            v_dir = _flat_grad_fill_none(g_dir, shared_params)
            v_doa = _flat_grad_fill_none(g_doa, shared_params)

            if v_dir is not None and v_doa is not None:
                cos = torch.dot(v_dir, v_doa) / (v_dir.norm() * v_doa.norm() + 1e-12)
                ratio = v_doa.norm() / (v_dir.norm() + 1e-12)
                print(f"[grad] cos(g_dir,g_doa)={cos.item():+.4f} | ||g_doa||/||g_dir||={ratio.item():.4f}")
                # print("dir None:", sum(g is None for g in g_dir), "/", len(g_dir),
                #       "doa None:", sum(g is None for g in g_doa), "/", len(g_doa))

        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
        dir_loss += U_dir.item()
        mse_loss += U_mse.item()
        recon_loss_epoch += recon_loss
        # DoA loss is returned as per-sample batch-mean (see models/lossfunction.py).
        # Keep logging/epoch stats in the same per-sample scale.
        try:
            doa_loss_epoch += float(_doa_loss.detach().cpu())
        except Exception:
            doa_loss_epoch += float(_doa_loss)

        try:
            fft_recon_loss_epoch += float(_fft_recon_loss.detach().cpu())
        except Exception:
            fft_recon_loss_epoch += float(_fft_recon_loss)

        try:
            phase_recon_loss_epoch += float(_phase_recon_loss.detach().cpu())
        except Exception:
            phase_recon_loss_epoch += float(_phase_recon_loss)

        if (k + 1) % 50 == 0 or (k + 1) == len(data_loader):
            S_numpy0 = 0.0
            if S is not None:
                S_list_numpy = S.detach().cpu().numpy()
                S_numpy = np.abs(S_list_numpy)
                S_numpy0 = S_numpy[0, 0]

            # DoA loss is already per-sample
            doa_loss_print = float(_doa_loss.detach().cpu()) if hasattr(_doa_loss, "detach") else float(_doa_loss)
            fft_loss_print = float(_fft_recon_loss.detach().cpu()) if hasattr(_fft_recon_loss, "detach") else float(_fft_recon_loss)
            phase_loss_print = float(_phase_recon_loss.detach().cpu()) if hasattr(_phase_recon_loss, "detach") else float(_phase_recon_loss)
            print(
                "Epoch: {}/{}, Batch: {}/{}, Loss: {:.4f}, DoA_loss: {:.6f} rad, U_dir: {:.4f}, U_mse: {:.4f}, S_mse: {:.4f}, recon_loss: {:.4f}, fft_recon: {:.6f}, phase_recon: {:.6f}, S_modelout: {:.4f}, lr: {:.6f}".format(
                    epoch_id + 1,
                    total_epochs,
                    k + 1,
                    len(data_loader),
                    loss.item(),
                    doa_loss_print,
                    U_dir.item(),
                    U_mse.item(),
                    S_mse,
                    recon_loss,
                    fft_loss_print,
                    phase_loss_print,
                    S_numpy0,
                    optimizer.param_groups[0]["lr"],
                )
            )
        k += 1

    num_batches = len(data_loader)
    return (
        epoch_loss / num_batches,
        dir_loss / num_batches,
        mse_loss / num_batches,
        recon_loss_epoch / num_batches,
        doa_loss_epoch / num_batches,
        fft_recon_loss_epoch / num_batches,
        phase_recon_loss_epoch / num_batches,
    )



@torch.no_grad()
def validate(model, data_loader, device, epoch_id: int, R: int, criterion: floss = None):
    model.eval()
    # IMPORTANT: to validate DoA loss, we must reuse the same criterion config as training
    # (especially lambda_doa/doa_mode). Fallback to default only if not provided.
    if criterion is None:
        criterion = _build_criterion(epoch_id, R)
    criterion = criterion.to(device)

    epoch_loss = 0.0
    dir_loss = 0.0
    mse_loss = 0.0
    recon_loss_epoch = 0.0
    doa_loss_epoch = 0.0
    fft_recon_loss_epoch = 0.0
    phase_recon_loss_epoch = 0.0

    for batch in data_loader:
        # Supports optional clean cov + doa targets (aligned with train_one_epoch)
        clean_inputs = None
        doa_gt_rad = None

        if len(batch) >= 5:
            if (
                isinstance(batch[1], torch.Tensor)
                and batch[1].dim() in (4, 5)
                and batch[1].size(-1) == 2
                and batch[1].size(-2) == batch[1].size(-3)
            ):
                inputs = batch[0]
                clean_inputs = batch[1]
                U_targets, S_targets, Vh_targets = batch[2], batch[3], batch[4]
                rest = batch[5:]
            else:
                inputs = batch[0]
                U_targets, S_targets, Vh_targets = batch[1], batch[2], batch[3]
                rest = batch[4:]
            if len(rest) >= 1:
                doa_gt_rad = rest[0]
        else:
            inputs, U_targets, S_targets, Vh_targets = batch

        inputs = inputs.to(device)
        U_targets = U_targets.to(device)
        S_targets = S_targets.to(device)
        Vh_targets = Vh_targets.to(device)
        if clean_inputs is not None:
            clean_inputs = clean_inputs.to(device)
        if doa_gt_rad is not None:
            doa_gt_rad = doa_gt_rad.to(device).to(torch.float32)

        want_fft_recon = float(getattr(criterion, "lambda_fft_recon", 0.0)) > 0
        want_phase_recon = float(getattr(criterion, "lambda_phase_recon", 0.0)) > 0
        want_aux = want_fft_recon or want_phase_recon
        if want_aux:
            if clean_inputs is None:
                raise ValueError("lambda_fft_recon>0 or lambda_phase_recon>0 but dataloader did not provide clean_inputs")
            out = model(inputs, return_aux=True)
        else:
            out = model(inputs)
        U, S, V = out[0], out[1], out[2]
        theta_deg = out[3] if len(out) > 3 else None

        aux = None
        if want_aux:
            aux = out[4]

        doa_pred_rad = None
        doa_gt_rad_use = None
        if getattr(criterion, "lambda_doa", 0.0) > 0:
            if doa_gt_rad is None:
                raise ValueError("lambda_doa>0 but dataloader did not provide doa_gt (radians)")
            if theta_deg is None:
                raise ValueError("lambda_doa>0 but theta_deg is None")
            if theta_deg.dim() == 1:
                doa_pred_rad = (theta_deg.view(-1, 1) * (math.pi / 180.0)).to(torch.float32)
            else:
                doa_pred_rad = (theta_deg * (math.pi / 180.0)).to(torch.float32)
            doa_gt_rad_use = doa_gt_rad.to(torch.float32)
            if doa_gt_rad_use.dim() == 1:
                doa_gt_rad_use = doa_gt_rad_use.view(-1, 1)
        fft_pred = None
        fft_target = None
        hd_pred = None
        hd_target = None
        if want_aux:
            clean_norm, _ = model.frobenius_norm_normalize(clean_inputs)
            clean_c = torch.view_as_complex(clean_norm.to(torch.float32))
            if bool(getattr(model, "use_diag_whiten", False)):
                clean_c = diag_whiten_hermitian(clean_c)
            if bool(getattr(model, "use_fba", False)):
                clean_c_ri = torch.view_as_real(clean_c)  # (B,N,N,2)
                clean_c_ri = clean_c_ri.permute(0, 3, 1, 2).contiguous()  # (B,2,N,N)
                clean_c = torch.view_as_complex(
                    apply_fba_ri(clean_c_ri).permute(0, 2, 3, 1).contiguous()
                )

            if want_fft_recon:
                fft_pred = aux["Hf_post"]
                fft_target = torch.fft.fft2(clean_c, norm="ortho")
            if want_phase_recon:
                hd_pred = aux["Hd_refined"]
                hd_target = clean_c

        loss, U_dir, Vh_dir, U_mse, V_mse, S_mse, recon_loss, _doa_loss, _fft_recon_loss, _phase_recon_loss = criterion(
            U_targets, S_targets, Vh_targets, U, S, V, epoch_id=epoch_id,
            doa_pred_rad=doa_pred_rad,
            doa_gt_rad=doa_gt_rad_use,
            fft_pred=fft_pred,
            fft_target=fft_target,
            hd_pred=hd_pred,
            hd_target=hd_target,
        )

        epoch_loss += loss.item()
        dir_loss += U_dir.item()
        mse_loss += U_mse.item()
        recon_loss_epoch += recon_loss
        try:
            doa_loss_epoch += float(_doa_loss.detach().cpu())
        except Exception:
            doa_loss_epoch += float(_doa_loss)
            
        try:
            fft_recon_loss_epoch += float(_fft_recon_loss.detach().cpu())
        except Exception:
            fft_recon_loss_epoch += float(_fft_recon_loss)

        try:
            phase_recon_loss_epoch += float(_phase_recon_loss.detach().cpu())
        except Exception:
            phase_recon_loss_epoch += float(_phase_recon_loss)

    num_batches = len(data_loader)
    return (
        epoch_loss / num_batches,
        dir_loss / num_batches,
        mse_loss / num_batches,
        recon_loss_epoch / num_batches,
        doa_loss_epoch / num_batches,
        fft_recon_loss_epoch / num_batches,
        phase_recon_loss_epoch / num_batches,
    )

def main():
    os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    args_data = build_arg_parser_data(
        phase=1,
        freeze_mode="none",
        freeze_spectral=False,
        grad_diag=False,
        lambda_dir=1.0,
        lambda_doa=1.0,
        lambda_fft_recon=1.0,
        lambda_phase_recon=1.0,
        N=8,
        M=2,
        rank=1,
        T=2,
        snr=5,
        signal_type="NarrowBand",
        signal_nature="coherent",
        eta=0.0,
        bias=0.0,
        sv_noise_var=0.0,
        train_ratio=0.8,
    ).parse_args()
    params = _build_params(
        N=args_data.N,
        M=args_data.M,
        T=args_data.T,
        snr=args_data.snr,
        signal_type=args_data.signal_type,
        signal_nature=args_data.signal_nature,
        eta=args_data.eta,
        bias=args_data.bias,
        sv_noise_var=args_data.sv_noise_var,
        doa_gap=args_data.doa_gap,
    )

    # Resolve suffix robustly (SNR formatting may be saved as 7 or 7.0)
    suffix = _build_suffix(params, args_data.T)
    try:
        snr_val = float(args_data.snr)
    except Exception:
        snr_val = None

    if snr_val is not None and float(snr_val).is_integer():
        # Build two candidates: int-like and float-like (7 vs 7.0)
        params_snr_int = _build_params(
            N=args_data.N,
            M=args_data.M,
            T=args_data.T,
            snr=int(snr_val),
            signal_type=args_data.signal_type,
            signal_nature=args_data.signal_nature,
            eta=args_data.eta,
            bias=args_data.bias,
            sv_noise_var=args_data.sv_noise_var,
            doa_gap=args_data.doa_gap,
        )
        params_snr_float = _build_params(
            N=args_data.N,
            M=args_data.M,
            T=args_data.T,
            snr=float(snr_val),
            signal_type=args_data.signal_type,
            signal_nature=args_data.signal_nature,
            eta=args_data.eta,
            bias=args_data.bias,
            sv_noise_var=args_data.sv_noise_var,
            doa_gap=args_data.doa_gap,
        )
        suffix_int = _build_suffix(params_snr_int, args_data.T)
        suffix_float = _build_suffix(params_snr_float, args_data.T)
        if suffix_int != suffix_float:
            cand = [suffix_int, suffix_float]
            found = None
            for s in cand:
                probe = "datasets/processed_cov_svd/" + f"iter_cov_noisy_step{s}.npy"
                if os.path.exists(probe):
                    found = s
                    break
            if found is not None and found != suffix:
                suffix = found
                print(f"[Suffix] Resolved dataset suffix by existing files: {suffix}")

    # Load processed DDCR covariance data.
    H_tensor_file = "datasets/processed_cov_svd/" + f"iter_cov_noisy_step{suffix}.npy"
    H_clean_file = "datasets/processed_cov_svd/" + f"iter_cov_clean_step{suffix}.npy"
    U_target_file = "datasets/processed_cov_svd/" + f"iter_u_target{suffix}.npy"
    S_target_file = "datasets/processed_cov_svd/" + f"svd_S{suffix}.npy"
    Vh_target_file = "datasets/processed_cov_svd/" + f"svd_Vh{suffix}.npy"
    doa_file = "datasets/generated_snapshots/" + f"doas{suffix}.npy"

    # ---- MUSIC sanity check (covariance -> DoA) ----
    # This uses ONLY numpy and the f_gendata.py outputs. It's helpful to tell whether
    # the covariance itself contains enough information to reach your target accuracy.
    if bool(getattr(args_data, "run_music", False)):
        cov_file = "datasets/generated_snapshots/" + f"covariances{suffix}.npy"
        if os.path.exists(cov_file) and os.path.exists(doa_file):
            max_sets = getattr(args_data, "music_max_sets", 500)
            max_sets = None if (max_sets is None or int(max_sets) <= 0) else int(max_sets)
            grid_num = int(getattr(args_data, "music_grid_num", 721))
            d_over_lambda = float(getattr(args_data, "music_d_over_lambda", 0.5))
            num_sources = int(getattr(args_data, "M", 1))

            rmse_deg_pi = music_rmse_deg(
                cov_file=cov_file,
                doa_file=doa_file,
                num_sources=num_sources,
                max_sets=max_sets,
                grid_min=-90.0,
                grid_max=90.0,
                grid_num=grid_num,
                d_over_lambda=d_over_lambda,
                wrap_period="pi",
            )
            rmse_deg_2pi = music_rmse_deg(
                cov_file=cov_file,
                doa_file=doa_file,
                num_sources=num_sources,
                max_sets=max_sets,
                grid_min=-90.0,
                grid_max=90.0,
                grid_num=grid_num,
                d_over_lambda=d_over_lambda,
                wrap_period="2pi",
            )
            print(
                f"[MUSIC] RMSE(pi-wrap)={rmse_deg_pi:.3f} deg | RMSE(2pi-wrap)={rmse_deg_2pi:.3f} deg "
                f"on covariances (sets={max_sets or 'all'}, grid={grid_num}, M={num_sources}, d/λ={d_over_lambda})"
            )
        else:
            print(f"[MUSIC] skip: missing files: {cov_file} or {doa_file}")
        if bool(getattr(args_data, "music_only", False)):
            return

    H_tensor = torch.tensor(np.load(H_tensor_file), device=device, dtype=torch.float32)
    # 加载干净协方差矩阵 (如果开启了 lambda_fft_recon 或 lambda_phase_recon)
    H_clean = None
    if float(getattr(args_data, "lambda_fft_recon", 0.0)) > 0 or float(getattr(args_data, "lambda_phase_recon", 0.0)) > 0:
        if not os.path.exists(H_clean_file):
            raise FileNotFoundError(f"lambda_fft_recon>0 or lambda_phase_recon>0 but clean cov file not found: {H_clean_file}")
        H_clean = torch.tensor(np.load(H_clean_file), device=device, dtype=torch.float32)
    U_target = torch.tensor(np.load(U_target_file), device=device, dtype=torch.float32)
    # S/Vh are kept as compatibility targets for the shared loss interface.
    S_target = torch.tensor(np.load(S_target_file), device=device, dtype=torch.float32)
    Vh_target = torch.tensor(np.load(Vh_target_file), device=device, dtype=torch.float32)

    doa_gt = None
    if os.path.exists(doa_file):
        doa_gt = torch.tensor(np.load(doa_file), device=device, dtype=torch.float32)

    # 统一实虚为最后一维，保持快拍维度一致
    # Processed files keep an intermediate step dimension; direct DDCR training
    # uses the first degraded covariance and predicts all M DoAs in one pass.
    H_tensor = H_tensor.reshape(-1, args_data.M, args_data.N, args_data.N, 2)
    if H_clean is not None:
        H_clean = H_clean.reshape(-1, args_data.M, args_data.N, args_data.N, 2)
    U_target = U_target.reshape(-1, args_data.M, args_data.N, 2)
    Vh_target = Vh_target.reshape(-1, args_data.N, 2)                                 # (T*M, N, 2)
    S_target = S_target.reshape(-1, 1)                                     # (T*M, 1)

    # Prepare DoA labels for direct multi-source training.
    doa_gt_train = None
    if doa_gt is not None:
        num_sets = int(H_tensor.shape[0])
        if int(doa_gt.shape[0]) != num_sets:
            m = min(int(doa_gt.shape[0]), num_sets)
            doa_gt = doa_gt[:m]
            H_tensor = H_tensor[:m]
            U_target = U_target[:m]
            if H_clean is not None:
                H_clean = H_clean[:m]
        if doa_gt.dim() == 1:
            doa_gt = doa_gt.view(-1, 1)
        num_sources = int(args_data.M)
        if int(doa_gt.shape[1]) < num_sources:
            raise ValueError(f"doas file provides only {int(doa_gt.shape[1])} sources but M={num_sources}")
        doa_gt_train = doa_gt[:, :num_sources]

    # 创建统一模型
    folder_path = f"datasets/weights/model{suffix}"
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    # direct multi-source: output r=M vectors per sample
    model = DDCRNet(M=args_data.M, N=args_data.N, r=args_data.rank, dim=128, depth=4, attn_dim=64, k_len=args_data.N,refine_mode="both").to(device)

    # 打印Flops（可选依赖 ptflops）
    if get_model_complexity_info is not None:
        flops, params = get_model_complexity_info(model, (args_data.N, args_data.N, 2), as_strings=True, print_per_layer_stat=True)
        print(f"Model complexity: {flops} FLOPS")
    else:
        print("ptflops not installed; skip FLOPs report")

    # 优化器参数设置
    weight_decay = float(getattr(args_data, "weight_decay", None) or 1e-4)  # 权重衰减
    batch_size = int(getattr(args_data, "batch_size", None) or 128)  # 每个batch的大小
    load_pretrained_model = bool(getattr(args_data, "pretrained_path", None))

    # warmup 后用余弦退火逐步衰减到极低学习率
    if load_pretrained_model:
        base_lr = 2.5e-4  # warmup 起点
        max_lr = 2.5e-4  # warmup 终点 / 余弦起点
        min_lr = 1e-6  # 余弦终点
        warmup = 10
        # 训练模型参数设置
        num_epochs = 100  # 总轮数
        num_sched_epochs = 80  # 学习率调度覆盖全程
    else:
        base_lr = 1e-3  # warmup 起点
        max_lr = 5e-3  # warmup 终点 / 余弦起点
        min_lr = 1e-4  # 余弦终点
        warmup = 30
        # 训练模型参数设置
        num_epochs = 200  # 总轮数
        num_sched_epochs = 180  # 学习率调度覆盖全程

    # Optional overrides (for automation / ablations)
    if getattr(args_data, "base_lr", None) is not None:
        base_lr = float(args_data.base_lr)
    if getattr(args_data, "max_lr", None) is not None:
        max_lr = float(args_data.max_lr)
    if getattr(args_data, "min_lr", None) is not None:
        min_lr = float(args_data.min_lr)
    if getattr(args_data, "warmup", None) is not None:
        warmup = int(args_data.warmup)
    if getattr(args_data, "num_epochs", None) is not None:
        num_epochs = int(args_data.num_epochs)
    if getattr(args_data, "num_sched_epochs", None) is not None:
        num_sched_epochs = int(args_data.num_sched_epochs)
    # Apply freeze mode for ablation experiments
    _apply_freeze_mode(model, getattr(args_data, "freeze_mode", "none"))

    # Explicit control for spectral_refine (separate switch as requested)
    if hasattr(model, "spectral_refine"):
        should_freeze_spectral = bool(getattr(args_data, "freeze_spectral", False))
        # If freeze_spectral is True -> Set requires_grad=False
        # If freeze_spectral is False -> Set requires_grad=True (override freeze_mode if needed)
        # This matches user requirement: "switch closed (False) -> open gradient", "switch open (True) -> freeze weights"
        _set_requires_grad(model.spectral_refine, not should_freeze_spectral)
        state_str = "Frozen" if should_freeze_spectral else "Trainable"
        print(f"Spectral Refinement module is set to: {state_str} (override)")

    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=base_lr,
        weight_decay=weight_decay,
    )

    # warmup + cosine scheduler
    warmup_epochs = warmup
    scheduler = get_scheduler(
        optimizer,
        warmup_epochs,
        num_sched_epochs,
        base_lr,
        max_lr,
        min_lr,
    )

    # load pre-trained model
    if load_pretrained_model:
        pre_trained_model_path = args_data.pretrained_path
        if os.path.exists(pre_trained_model_path):
            model.load_state_dict(torch.load(pre_trained_model_path))
            print(f"Pre-trained model loaded from {pre_trained_model_path}")
        else:
            raise FileNotFoundError(f"Pretrained weights not found: {pre_trained_model_path}")

    # Create a direct single-step dataset for DDCR training.
    H_in = H_tensor[:, 0]
    U_in = U_target.permute(0, 2, 1, 3).contiguous()
    S_in = torch.zeros((H_in.shape[0], args_data.M), device=device, dtype=torch.float32)
    Vh_in = torch.zeros((H_in.shape[0], args_data.N, args_data.M, 2), device=device, dtype=torch.float32)
    H_clean_in = H_clean[:, 0] if H_clean is not None else None

    if args_data.lambda_doa > 0:
        if doa_gt_train is None:
            raise FileNotFoundError(f"lambda_doa>0 but DoA file not found: {doa_file}")
        if H_clean_in is not None:
            dataset = TensorDataset(H_in, H_clean_in, U_in, S_in, Vh_in, doa_gt_train)
        else:
            dataset = TensorDataset(H_in, U_in, S_in, Vh_in, doa_gt_train)
    else:
        if H_clean_in is not None:
            dataset = TensorDataset(H_in, H_clean_in, U_in, S_in, Vh_in)
        else:
            dataset = TensorDataset(H_in, U_in, S_in, Vh_in)
    # 设置训练集/测试集比例
    train_ratio = max(0.0, min(1.0, args_data.train_ratio))
    train_size = int(train_ratio * len(dataset))
    test_size = len(dataset) - train_size
    if train_size == 0:
        raise ValueError("train_ratio 太小，导致没有训练样本")
    # 划分（可复现）
    split_seed = int(getattr(args_data, "split_seed", 42))
    split_gen = None if split_seed < 0 else torch.Generator().manual_seed(split_seed)
    train_dataset, test_dataset = random_split(dataset, [train_size, test_size], generator=split_gen)
    if split_seed < 0:
        print(f"Split: train={train_size}, test={test_size} | split_seed=non-deterministic")
    else:
        print(f"Split: train={train_size}, test={test_size} | split_seed={split_seed}")
    # 数据加载器
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False) if test_size > 0 else None

    print("Start training...")
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(
        f"Freeze mode: {getattr(args_data,'freeze_mode','none')} "
        f"| trainable params: {trainable_params}/{total_params}"
    )
    loss_list = []
    val_loss_list = []
    # Save separate DoA loss curves only when enabled.
    doa_loss_list = [] if float(getattr(args_data, "lambda_doa", 0.0)) > 0 else None
    val_doa_loss_list = [] if float(getattr(args_data, "lambda_doa", 0.0)) > 0 else None
    best_model_state = None
    best_loss = np.inf

    for epoch in range(num_epochs):
        model.set_tau_s(epoch_id=epoch)
        begin_time = time.time()
        criterion = floss(
            lambda1=float(args_data.lambda_dir),
            lambda2=0.0,
            lambda3=0.0,
            lambda4=0.0,
            lambda5=0.0,
            lambda6=0.0,
            lambda_doa=float(args_data.lambda_doa),
            doa_mode=str(args_data.doa_mode),
            dir_mode=str(getattr(args_data, "dir_mode", "vector")),
            R=args_data.rank,
            lambda_fft_recon=float(getattr(args_data, "lambda_fft_recon", 0.0)),
            fft_recon_mode=str(getattr(args_data, "fft_recon_mode", "mag_l1")),
            lambda_phase_recon=float(getattr(args_data, "lambda_phase_recon", 0.0)),
            dir_effective_rank="full",
        ).to(device)
        train_loss, train_dir, train_mse, train_recon, train_doa, train_fft_recon, train_phase_recon = train_one_epoch(
            model,
            train_loader,
            optimizer,
            device,
            epoch,
            args_data.M,
            num_epochs,
            criterion=criterion,
            args_data=args_data,
        )

        if epoch < num_sched_epochs:
            scheduler.step()

        val_metrics = None
        if val_loader is not None and len(val_loader) > 0:
            val_metrics = validate(model, val_loader, device, epoch, args_data.M, criterion=criterion)

        end_time = time.time()
        epoch_time = end_time - begin_time

        loss_list.append(train_loss)
        if doa_loss_list is not None:
            # train_doa is already a scalar (float/tensor); keep per-epoch mean.
            doa_loss_list.append(float(train_doa))
        if val_metrics:
            # validate may return:
            #   (loss, dir, mse, recon, doa)
            #   (loss, dir, mse, recon, doa, fft_recon)
            #   (loss, dir, mse, recon, doa, fft_recon, phase_recon)
            val_phase_recon = 0.0
            if len(val_metrics) == 7:
                val_loss, val_dir, val_mse, val_recon, val_doa, val_fft_recon, val_phase_recon = val_metrics
            elif len(val_metrics) == 6:
                val_loss, val_dir, val_mse, val_recon, val_doa, val_fft_recon = val_metrics
            elif len(val_metrics) == 5:
                val_loss, val_dir, val_mse, val_recon, val_doa = val_metrics
                val_fft_recon = 0.0
            else:
                val_loss, val_dir, val_mse, val_recon = val_metrics
                val_doa = 0.0
                val_fft_recon = 0.0
            val_loss_list.append(val_loss)
            if val_doa_loss_list is not None:
                val_doa_loss_list.append(float(val_doa))

        print(
            f"Epoch {epoch+1}/{num_epochs} | train loss {train_loss:.4f}, doa {float(train_doa):.4f}, dir {train_dir:.4f}, mse {train_mse:.4f}, recon {train_recon:.4f}"
        )
        if val_metrics:
            print(f"               val loss {val_loss:.4f}, doa {float(val_doa):.4f}, dir {val_dir:.4f}, mse {val_mse:.4f}, recon {val_recon:.4f}, fft_recon {val_fft_recon:.4f}, phase_recon {val_phase_recon:.4f}, time {epoch_time:.1f}s")
        else:
            print(f"              time {epoch_time:.1f}s (no val set)")

        metric_for_selection = val_metrics[0] if val_metrics else train_loss
        if metric_for_selection < best_loss:
            best_loss = metric_for_selection
            best_model_state = model.state_dict().copy()
            print("New best model updated")

            # Save best checkpoint and loss curves.
            tag = str(getattr(args_data, "model_tag", "") or "").strip()
            model_save_name = "model_trained.pth" if not tag else f"model_trained_{tag}.pth"
            model_save_path = f"datasets/weights/model{suffix}/{model_save_name}"
            if best_model_state is not None:
                torch.save(best_model_state, model_save_path)
                print(f"Best model saved to {model_save_path}, best metric {best_loss:.4f}")
            else:
                print("Warning: No model was saved")

            loss_file_name = "model_train_loss.txt" if not tag else f"model_train_loss_{tag}.txt"
            loss_file_path = f"datasets/weights/model{suffix}/{loss_file_name}"
            np.savetxt(loss_file_path, np.array(loss_list), fmt='%.6f')
            saved_loss_files = [("train_total_loss", loss_file_path)]

            if doa_loss_list is not None:
                doa_loss_file_name = "model_train_doa_loss.txt" if not tag else f"model_train_doa_loss_{tag}.txt"
                doa_loss_file_path = f"datasets/weights/model{suffix}/{doa_loss_file_name}"
                np.savetxt(doa_loss_file_path, np.array(doa_loss_list), fmt='%.6f')
                saved_loss_files.append(("train_doa_loss", doa_loss_file_path))

            if val_loss_list:
                val_loss_file_name = "model_val_loss.txt" if not tag else f"model_val_loss_{tag}.txt"
                val_loss_file_path = f"datasets/weights/model{suffix}/{val_loss_file_name}"
                np.savetxt(val_loss_file_path, np.array(val_loss_list), fmt='%.6f')
                saved_loss_files.append(("val_total_loss", val_loss_file_path))
                if val_doa_loss_list is not None:
                    val_doa_loss_file_name = "model_val_doa_loss.txt" if not tag else f"model_val_doa_loss_{tag}.txt"
                    val_doa_loss_file_path = f"datasets/weights/model{suffix}/{val_doa_loss_file_name}"
                    np.savetxt(val_doa_loss_file_path, np.array(val_doa_loss_list), fmt='%.6f')
                    saved_loss_files.append(("val_doa_loss", val_doa_loss_file_path))
            else:
                print("No validation loss saved because validation set is empty.")

            print("Saved loss curves:")
            for loss_name, path in saved_loss_files:
                print(f"  - {loss_name}: {path}")

    print(f"Unified model training completed!")

if __name__ == "__main__":
    main()
